Extract image uploader component
teamyapp/teamy-web pull request #313
Opened 2022-08-03 01:50 UTC by duanxianbo

extract image uploader

2022-08-03 02:12 UTC, naturetime10 commented
Let's start PR title with uppercase letter

2022-08-03 05:16 UTC, naturetime10 requested changes

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/Modals/UserSettingsModal.component.tsx
> +                        <div className={styles.ImageUploaderComponentWrapper}>
```suggestion
                        <div className={styles.UserProfileUploader}>
```

2022-08-03 05:16 UTC, naturetime10 commented on src/libs/identity/config.ts
>  };
Undo changes in this file.

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/ImageUploader.component.module.scss
> +    height: var(--image-uploader-height, 150px);
Let's define scss variables at the top of this file to hold the value of `var(--image-uploader-height, 150px)` so that we can a centralized place to find how to customize this component.

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/ImageUploader.component.module.scss
> +    width: var(--image-uploader-width, 150px);
Same as the comment above.

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/ImageUploader.component.tsx
> +    imageValidator?: (image: HTMLImageElement) => boolean;
```suggestion
    validateNewImage?: (image: HTMLImageElement) => boolean;
```

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/ImageUploader.component.tsx
> +    imageUrl?: string;
```suggestion
    activeImageUrl?: string;
```

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/ImageUploader.component.tsx
> +    onFileUploadFinished: (fileUploadSessionId: number) => Promise<void>;
Let's move events after placeholder field.

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/ImageUploader.component.tsx
> +    uploadLabel: string;
```suggestion
    uploadButtonLabel: string;
```

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/ImageUploader.component.tsx
> +    placeholder?: string;
```suggestion
    emptyImagePlaceholder?: string;
```

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/ImageUploader.component.tsx
> +    onFileUploadFinished: (fileUploadSessionId: number) => Promise<void>;
```suggestion
    onFileUploadFinished?: (fileUploadSessionId: number) => Promise<void>;
```

Let's make this callback optional. The parent of this callback may decide they are not interested in doing anything when this happens and hence doesn't pass in anything.

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/ImageUploader.component.tsx
> +    onFileUploadInit: () => Promise<number>;
```suggestion
    createRemoteFileUploadSession: () => Promise<number>;
```

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/ImageUploader.component.tsx
> +    isPreviewingImage: boolean;
```suggestion
    showPreview: boolean;
```

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/ImageUploader.component.tsx
> +    }
Let's move this after the constructor so that it's easier for reader to follow the code.

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/ImageUploader.component.tsx
> +        if (this.props.imageValidator && !this.props.imageValidator.call(this, image)) {
```suggestion
        if (this.props.imageValidator && !this.props.imageValidator.call(null, image)) {
```

Let's pass null instead. External parent shouldn't have access to the data inside component.

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/ImageUploader.component.tsx
> +
```suggestion
```

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/Modals/UserSettingsModal.component.module.scss
> +            .ImageUploaderComponentWrapper {
```suggestion
            .UserProfileUploader {
```

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/Modals/UserSettingsModal.component.tsx
> +    private userProfileImageValidator(image: HTMLImageElement) {
```suggestion
    private validateUserProfileImage(image: HTMLImageElement) {
```

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/Modals/UserSettingsModal.component.tsx
> +                                imageAlt={`${this.state.editingUserFirstName} ${this.state.editingUserLastName}`}
Let's define a variable called fullName between line 157 and line 158.

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/Modals/UserSettingsModal.component.tsx
> +                                    this.state.editingUserFirstName &&
Let's define profileImagePlaceholder variable.

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/Modals/UserSettingsModal.component.tsx
> +    private async handleFileUploadFinished(fileUploadSessionId: number) {
```suggestion
    private async handleFileUploadFinished = (fileUploadSessionId: number) => {
```
Let's use `=>` so that scope for createUserProfileUpdateSession automatically bind to `this`.

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/Modals/UserSettingsModal.component.tsx
> +                                onFileUploadInit={this.stateSyncer.createUserProfileUpdateSession.bind(
Let's update `createUserProfileUpdateSession` in `stateSyncer` to use `=>` so that scope for createUserProfileUpdateSession automatically bind to `stateSyncer`.

2022-08-03 05:16 UTC, naturetime10 commented on src/components/internal/Modals/UserSettingsModal.component.tsx
> +                                    this,
Use '=>' instead of bind.

2022-08-03 22:11 UTC, duanxianbo commented on src/libs/identity/config.ts
>  };
done

2022-08-03 22:12 UTC, duanxianbo commented on src/components/internal/ImageUploader.component.module.scss
> +    height: var(--image-uploader-height, 150px);
done

2022-08-03 22:12 UTC, duanxianbo commented on src/components/internal/ImageUploader.component.module.scss
> +    width: var(--image-uploader-width, 150px);
done

2022-08-03 22:12 UTC, duanxianbo commented on src/components/internal/Modals/UserSettingsModal.component.tsx
> +                                imageAlt={`${this.state.editingUserFirstName} ${this.state.editingUserLastName}`}
done

2022-08-03 22:13 UTC, duanxianbo commented on src/components/internal/Modals/UserSettingsModal.component.tsx
> +                                    this.state.editingUserFirstName &&
done

2022-08-03 22:13 UTC, duanxianbo commented on src/components/internal/Modals/UserSettingsModal.component.tsx
> +                                onFileUploadInit={this.stateSyncer.createUserProfileUpdateSession.bind(
done

2022-08-03 22:13 UTC, duanxianbo commented on src/components/internal/Modals/UserSettingsModal.component.tsx
> +                                    this,
done

2022-08-03 22:16 UTC, duanxianbo commented on src/components/internal/ImageUploader.component.tsx
> +    onFileUploadFinished: (fileUploadSessionId: number) => Promise<void>;
done

2022-08-03 22:16 UTC, duanxianbo commented on src/components/internal/ImageUploader.component.tsx
> +    }
done

2022-08-04 00:21 UTC, naturetime10 approved these changes

2022-08-04 00:21 UTC, naturetime10 commented on src/components/internal/ImageUploader.component.tsx
> +
```suggestion
```

2022-08-04 00:26 UTC, merged