Move tasks to next sprint on single click
teamyapp/teamy-web pull request #320
Opened 2022-08-10 13:17 UTC by duanxianbo

<img width="768" alt="image" src="https://user-images.githubusercontent.com/6356492/184279009-2f1b44d5-302b-4471-b10e-55df615034d4.png">

2022-08-11 05:31 UTC, naturetime10 commented
Thanks for creating this PR! It's challenging to understand the final effect of HTML & CSS changes in this PR. Can you add a screenshot in PR description?

2022-08-11 06:38 UTC, naturetime10 requested changes

2022-08-11 06:38 UTC, naturetime10 commented on src/client/sprint.client.ts
> +                            isPlanned
I think this is not needed. `IsPlanned` shouldn't change when moving between sprints.

2022-08-11 06:38 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +
```suggestion
```

2022-08-11 06:38 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +
```suggestion
```

2022-08-11 06:38 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +        return this.state.sprints[currentIndex - 1];
I would recommend we find the next sprint by first make a copy of sprints array with `map`. Then find the index of the current sprint. We can't assume `sprints` are sorted.

2022-08-11 06:38 UTC, naturetime10 commented on src/data/task.filter.ts
> +    task.status !== 'DELIVERED';
Can we rename `nonDelivered` to unfinished, which I feel is more natural.

2022-08-11 06:38 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +
```suggestion
```

2022-08-11 06:38 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +    private async _moveTasksToSprint(
Are we using this function somewhere else? If not, why are we creating a helper function?

2022-08-11 06:38 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +
```suggestion
```

2022-08-11 06:38 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +            const taskId = toInt(remoteTask.id);
Maybe extra to helper function and call it `updateTaskSprint`?

2022-08-11 06:38 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +            const taskId = toInt(remoteTask.id);
This is a good use of reduce function. Moving forwards, we can refactor our codebase to use this pattern.

2022-08-12 03:18 UTC, duanxianbo commented on src/components/internal/SprintsHeaderSection.component.tsx
> +        return this.state.sprints[currentIndex - 1];
done

2022-08-12 03:18 UTC, duanxianbo commented on src/storage/syncer/stateSyncer.ts
> +    private async _moveTasksToSprint(
moved

2022-08-12 03:19 UTC, duanxianbo commented on src/storage/syncer/stateSyncer.ts
> +            const taskId = toInt(remoteTask.id);
done

2022-08-12 04:07 UTC, naturetime10 requested changes

2022-08-12 04:07 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +
```suggestion
```

2022-08-12 04:07 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +        const nonDelivereTasks = (currentSprint.tasks || []).filter(
```suggestion
        const unfinishedTasks = (currentSprint.tasks || []).filter(
```

2022-08-12 04:07 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +        if (!nonDelivereTasks.length) {
```suggestion
        if (!unfinishedTasks.length) {
```

2022-08-12 04:07 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +            alert('can not move to next sprint');
```suggestion
            alert('can not move tasks to next sprint');
```

2022-08-12 04:07 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +        const nonDelivereTasks = (currentSprint.tasks || []).filter(
```suggestion
        const unfinishedTasks = (currentSprint.tasks || []).filter(
```

2022-08-12 04:07 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +        const nonDelivereTaskIds = nonDelivereTasks.map((task) => task.id);
```suggestion
        const unfinishedTaskIds = unfinishedTasks.map((task) => task.id);
```

2022-08-12 04:07 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +            nonDelivereTaskIds,
```suggestion
            unfinishedTaskIds,
```

2022-08-12 04:07 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +
```suggestion
```

2022-08-12 04:07 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +        return sprints[currentIndex - 1];
Next PR: handle the case when next sprint doesn't exist

2022-08-12 04:07 UTC, naturetime10 commented on src/components/internal/shared.scss
> +
```suggestion
```

2022-08-12 04:07 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +
```suggestion
```

2022-08-12 04:07 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +        appState = mergeTask(appState, remoteTask);
```suggestion
        }
        
        appState = mergeTask(appState, remoteTask);
```

2022-08-12 04:07 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +
```suggestion
```

2022-08-12 04:08 UTC, naturetime10 approved these changes

2022-08-12 04:09 UTC, merged