Allow user to open team's context menu on header
teamyapp/teamy-web pull request #337
Opened 2022-08-21 00:37 UTC by ShenshunYao

2022-08-21 01:39 UTC, duanxianbo submitted a review, later dismissed

2022-08-21 01:39 UTC, duanxianbo commented on src/components/internal/Header.component.tsx
> +                    )}
can we move those to a seperate component?

2022-08-21 01:39 UTC, duanxianbo commented on src/components/internal/Header.component.tsx
> +        this.props.onAddTeamMembersClick?.call(null, this.selectedTeamId || -1);
if there is no valid teamId,  I think we just donot call the function instead of pass -1

2022-08-21 01:55 UTC, naturetime10 requested changes

2022-08-21 01:55 UTC, naturetime10 commented on src/components/internal/Header.component.tsx
> +            teamContextMenuLeft: -1000,
```suggestion
            teamContextMenuLeft: 0,
```

2022-08-21 01:55 UTC, naturetime10 commented on src/components/internal/Header.component.tsx
> +            teamContextMenuTop: -1000,
```suggestion
            teamContextMenuTop: 0,
```

2022-08-21 01:55 UTC, naturetime10 commented on src/components/internal/Header.component.tsx
> +            teamContextMenuLeft: -1000,
If contextMenu is not showing yet, I think we can set both left and top to zero.

2022-08-21 01:55 UTC, naturetime10 commented on src/components/internal/Header.component.tsx
> +                            tabIndex={-1}
Just a knowledge check. Do you understand why we are setting `-1` here?

2022-08-21 01:55 UTC, naturetime10 commented on src/components/internal/Header.component.tsx
> +                    )}
I agree with @duanxianbo that we should consider refactoring into a separate component to encapsulate logic and to encourage code reuse.

2022-08-21 01:55 UTC, naturetime10 commented on src/components/internal/Header.component.tsx
> +        this.props.onAddTeamMembersClick?.call(null, this.selectedTeamId || -1);
I think we should skip this function call if there is no valid team ID.

2022-08-21 01:55 UTC, naturetime10 commented on src/components/internal/Header.component.tsx
> +        this.selectedTeamId = teamId;
I think this not needed. you can directly read from `this.props.currentTeam?.id` in `onAddMembersClick`

2022-08-21 01:55 UTC, naturetime10 commented on src/components/internal/Header.component.tsx
> +            teamContextMenuLeft: -1000,
```suggestion
            teamContextMenuLeft: 0,
```

2022-08-21 01:55 UTC, naturetime10 commented on src/components/internal/Header.component.tsx
> +            teamContextMenuTop: -1000,
```suggestion
            teamContextMenuTop: 0,
```

2022-08-21 01:55 UTC, naturetime10 commented on src/components/internal/Header.component.tsx
> +            this.selectedTeamId || -1,
Skip this function call if `this.selectedTeamId` is undefined.

2022-08-21 01:55 UTC, naturetime10 commented on src/components/internal/Header.component.tsx
> +        this.props.onShowInvitationsClick?.call(
Skip this function call if `this.selectedTeamId` is undefined.

2022-08-21 01:55 UTC, naturetime10 commented on src/components/internal/Header.component.tsx
> +        );
Skip this function call if `this.selectedTeamId` is undefined.

2022-08-21 22:40 UTC, naturetime10 requested changes
I think it's okey to extract team context menu into a separate component in the next PR.

2022-08-21 22:40 UTC, naturetime10 commented on src/components/internal/Header.component.tsx
> +
```suggestion
```

2022-08-21 22:40 UTC, naturetime10 commented on src/components/internal/Header.component.tsx
> +            this.closeTeamContextMenu();
We should always close context menu no matter current team ID is `undefined` or not.

2022-08-21 22:40 UTC, naturetime10 commented on src/components/internal/Header.component.tsx
> +            this.closeTeamContextMenu();
We should always close context menu no matter current team ID is `undefined` or not.

2022-08-21 22:40 UTC, naturetime10 commented on src/components/internal/Header.component.tsx
> +            this.closeTeamContextMenu();
We should always close context menu no matter current team ID is `undefined` or not.

2022-08-21 22:40 UTC, naturetime10 commented on src/components/internal/Header.component.tsx
> +            this.closeTeamContextMenu();
We should always close context menu no matter current team ID is `undefined` or not.

2022-08-25 00:23 UTC, naturetime10 requested changes

2022-08-25 00:23 UTC, naturetime10 commented on src/components/internal/Drawer.tsx
> +            teamContextMenuTop: 0,
I think you don't need any of them. Let's remove those.

2022-08-25 00:23 UTC, naturetime10 commented on src/components/internal/Header.component.module.scss
> +$contextMenuSidePadding: 20px;
```suggestion
```

2022-08-25 00:23 UTC, naturetime10 commented on src/components/internal/TeamContextMenu.component.tsx
> +    private contextMenuRef: RefObject<any> = createRef();
```suggestion
    private contextMenuRef = createRef<HTMLULElement>();
```

2022-08-25 01:01 UTC, naturetime10 requested changes

2022-08-25 01:01 UTC, naturetime10 commented on src/components/internal/Drawer.tsx
> +        debugger;
```suggestion
```

2022-08-25 01:01 UTC, naturetime10 approved these changes

2022-08-25 02:33 UTC, naturetime10 requested changes

2022-08-25 02:33 UTC, naturetime10 commented on src/components/internal/Drawer.tsx
> +            teamContextMenuTop: 0,
Those need to be removed.

2022-08-25 03:35 UTC, naturetime10 approved these changes

2022-08-25 03:37 UTC, merged