Assgin to me when moving from backlog
teamyapp/teamy-web pull request #338
Opened 2022-08-21 01:34 UTC by duanxianbo

2022-08-21 01:44 UTC, duanxianbo commented
there is some irelevant change because of my vscode lint

2022-08-21 20:36 UTC, naturetime10 requested changes

2022-08-21 20:36 UTC, naturetime10 commented on src/libs/dragAndDrop/DragAndDropController.ts
> +}
Drag & drop is an independent library. We should avoid hard coding application specific data in this library.

2022-08-21 20:42 UTC, naturetime10 requested changes

2022-08-21 20:42 UTC, naturetime10 commented on src/libs/dragAndDrop/DragAndDropController.ts
> +}
Let's pass in a generic parameter `Context` to `DragAndDropController`

2022-08-22 01:51 UTC, naturetime10 approved these changes

2022-08-22 02:04 UTC, merged