Add smart relative position
teamyapp/teamy-web pull request #356
Opened 2022-08-30 01:20 UTC by duanxianbo

2022-08-30 03:49 UTC, naturetime10 requested changes

2022-08-30 03:49 UTC, naturetime10 commented on src/libs/layout/relativeLayout.ts
> +export type OverSpaceAction = 'overlap' | 'horizontalShift' | 'verticalShift';
```suggestion
export type OverSpaceAction = 'overlap' | 'shiftHorizontal' | 'shiftVertical';
```

2022-08-30 03:49 UTC, naturetime10 commented on src/libs/layout/relativeLayout.ts
> +        window.innerWidth || document.documentElement.clientWidth;
```suggestion
    }
    
    const rightBound =
        (window.innerWidth || document.documentElement.clientWidth) - offset;
```

2022-08-30 03:49 UTC, naturetime10 commented on src/libs/layout/relativeLayout.ts
> +    if (left >= 0 && right <= windowRight) {
```suggestion
    if (left >= offset && right <= rightBound) {
```

2022-08-30 03:49 UTC, naturetime10 commented on src/libs/layout/relativeLayout.ts
>      }
if (left < offset) {
   switch (overSpaceAction) {
      case :
         return
   }

if (right > rightBound) {
   switch (overSpaceAction) {
      case :
         return
   }
}

return left.

Let's do the same for calcTop. Hope this is making logic more clear and easier to understand.

2022-08-30 21:27 UTC, duanxianbo commented on src/libs/layout/relativeLayout.ts
>      }
done

2022-08-31 01:00 UTC, naturetime10 approved these changes

2022-08-31 01:00 UTC, merged