Add relative layout to calendar
teamyapp/teamy-web pull request #362
Opened 2022-09-01 01:38 UTC by duanxianbo

2022-09-01 03:28 UTC, naturetime10 requested changes

2022-09-01 03:28 UTC, naturetime10 commented on src/components/internal/FilterList.component.tsx
> +                            zOffset={101}
Can we move this constant to the top of this file and give it a meaningful name?

2022-09-01 03:28 UTC, naturetime10 commented on src/components/internal/FilterList.component.tsx
> +                            zOffset={101}
Can we move this constant to the top of this file and give it a meaningful name?

2022-09-01 03:28 UTC, naturetime10 commented on src/components/internal/Modals/CreateSprintModal.component.tsx
> +                            zOffset={1002}
Can we move this constant to the top of this file and give it a meaningful name?

2022-09-01 03:28 UTC, naturetime10 commented on src/components/internal/Modals/TaskDetailModal.component.tsx
> +                                            relativeLayout={this.props.deps.relativeLayout}
Can we move this constant to the top of this file and give it a meaningful name?

2022-09-01 03:28 UTC, naturetime10 commented on src/libs/ui/DatePickerContainer.tsx
> +} from '../../components/internal/PopupContainer';
Libs should only reference external package or other libs. Can we move `PopupContainer` into @libs/ui ?

2022-09-01 03:28 UTC, naturetime10 commented on src/components/internal/DurationInput.ui.tsx
> +                    trigger={({ onToggle }) => (
```suggestion
                    renderReferenceElement={({ onToggle }) => (
```

2022-09-01 03:28 UTC, naturetime10 commented on src/components/internal/DurationInput.ui.tsx
> +                    target={({ onClose }) => (
```suggestion
                    renderPopup={({ onClose }) => (
```

2022-09-01 03:28 UTC, naturetime10 commented on src/components/internal/Modals/CreateSprintModal.component.tsx
> +                            zOffset={1002}
Can we move this constant to the top of this file and give it a meaningful name?

2022-09-01 03:28 UTC, naturetime10 commented on src/components/internal/FilterList.component.tsx
> +                            zOffset={101}
Recommend naming: xxxxxZIndex
zOffset={xxxxxZIndex + 1}

2022-09-01 03:28 UTC, naturetime10 commented on src/components/internal/Modals/TaskDetailModal.component.tsx
> +                                            zOffset={1002}
Can we move this constant to the top of this file and give it a meaningful name?

2022-09-01 12:41 UTC, duanxianbo commented on src/components/internal/FilterList.component.tsx
> +                            zOffset={101}
done

2022-09-01 12:43 UTC, duanxianbo commented on src/components/internal/FilterList.component.tsx
> +                            zOffset={101}
should we change it to snack_case as it is a constant?

2022-09-01 12:43 UTC, duanxianbo commented on src/components/internal/Modals/CreateSprintModal.component.tsx
> +                            zOffset={1002}
done

2022-09-01 12:43 UTC, duanxianbo commented on src/components/internal/Modals/TaskDetailModal.component.tsx
> +                                            relativeLayout={this.props.deps.relativeLayout}
done

2022-09-01 12:43 UTC, duanxianbo commented on src/libs/ui/DatePickerContainer.tsx
> +} from '../../components/internal/PopupContainer';
changed name and moved to the ui/layout folder

2022-09-01 12:43 UTC, duanxianbo commented on src/components/internal/Modals/CreateSprintModal.component.tsx
> +                            zOffset={1002}
done

2022-09-01 12:43 UTC, duanxianbo commented on src/components/internal/Modals/TaskDetailModal.component.tsx
> +                                            zOffset={1002}
done

2022-09-02 01:48 UTC, naturetime10 requested changes

2022-09-02 01:48 UTC, naturetime10 commented on src/components/internal/DurationInput.ui.tsx
> +
```suggestion
```

2022-09-02 01:48 UTC, naturetime10 commented on src/components/internal/DurationInput.ui.tsx
> +                    renderPopup={({ onClose }) => (
```suggestion
                    renderFollower={({ onClose }) => (
```

2022-09-02 01:48 UTC, naturetime10 commented on src/components/internal/FilterList.component.tsx
> +                            zOffset={DATE_PICKER_ZINDEX}
```suggestion
                            zOffset={DATE_PICKER_Z_INDEX}
```

2022-09-02 01:48 UTC, naturetime10 commented on src/components/internal/FilterList.component.tsx
> +                            zOffset={DATE_PICKER_ZINDEX}
```suggestion
                            zOffset={DATE_PICKER_Z_INDEX}
```

2022-09-02 01:48 UTC, naturetime10 commented on src/components/internal/Modals/CreateSprintModal.component.tsx
> +const DATE_PICKER_ZINDEX = 1002
```suggestion
const DATE_PICKER_Z_INDEX = 1002;
```

2022-09-02 01:48 UTC, naturetime10 commented on src/components/internal/Modals/CreateSprintModal.component.tsx
> +                            zOffset={DATE_PICKER_ZINDEX}
```suggestion
                            zOffset={DATE_PICKER_Z_INDEX}
```

2022-09-02 01:48 UTC, naturetime10 commented on src/components/internal/Modals/TaskDetailModal.component.tsx
> +const DATE_PICKER_ZINDEX = 1002
```suggestion
const DATE_PICKER_Z_INDEX = 1002;
```

2022-09-02 01:48 UTC, naturetime10 commented on src/components/internal/Modals/TaskDetailModal.component.tsx
> +const DURATION_INPUT_ZINDEX = 1000
```suggestion
const DURATION_INPUT_Z_INDEX = 1000;

```

2022-09-02 01:48 UTC, naturetime10 commented on src/libs/layout/RelativeLayoutContainer.tsx
> +    renderPopup: ({
```suggestion
    renderFollower: ({
```

2022-09-02 01:48 UTC, naturetime10 commented on src/libs/layout/RelativeLayoutContainer.tsx
>      private readonly triggerRef = createRef<HTMLDivElement>();
Discussed offline. Please change all `popup` keyword in this PR to `follower`

2022-09-02 01:48 UTC, naturetime10 commented on src/libs/ui/DatePickerContainer.tsx
>  import { today } from '../../components/internal/format';
Can we only reference helpers from ui?

2022-09-02 01:48 UTC, naturetime10 commented on src/libs/ui/DatePickerContainer.tsx
> +
```suggestion
```

2022-09-02 01:48 UTC, naturetime10 commented on tsconfig.json
> +  "extends": "./tsconfig.path.json",
Let's add it to .gitignore

2022-09-02 02:57 UTC, duanxianbo commented on src/libs/ui/DatePickerContainer.tsx
>  import { today } from '../../components/internal/format';
done

2022-09-02 02:57 UTC, duanxianbo commented on tsconfig.json
> +  "extends": "./tsconfig.path.json",
done

2022-09-02 02:57 UTC, duanxianbo commented on src/libs/layout/RelativeLayoutContainer.tsx
>      private readonly triggerRef = createRef<HTMLDivElement>();
done

2022-09-02 03:07 UTC, naturetime10 approved these changes

2022-09-02 03:07 UTC, merged