Add dragging task by user
teamyapp/teamy-web pull request #370
Opened 2022-09-16 02:56 UTC by duanxianbo

![image](https://user-images.githubusercontent.com/6356492/193307167-0a5e6edd-6a53-41f7-958a-a76dd5e4f7ec.png)

2022-09-23 06:50 UTC, naturetime10 requested changes

2022-09-23 06:50 UTC, naturetime10 commented on src/components/App.component.tsx
> +                await this.stateSyncer.setInitialStateReceived()
```suggestion
                await this.stateSyncer.setInitialStateReady()
```

2022-09-23 06:50 UTC, naturetime10 commented on src/components/internal/InlineTask.tsx
> +                >
Use `classNames`.  Can we add this class to line 75?

2022-09-23 06:50 UTC, naturetime10 commented on src/client/task.client.ts
> +    }
```suggestion
    }
    
```

2022-09-23 06:50 UTC, naturetime10 commented on src/components/App.component.tsx
> +                await this.stateSyncer.setInitialStateReceived()
```suggestion
                await this.stateSyncer.setInitialStateReceived();
```

2022-09-23 06:50 UTC, naturetime10 commented on src/components/App.component.tsx
> +                await this.stateSyncer.setInitialStateReceived()
So we won't send initialStateReceived signal if we are showing task modal?

2022-09-23 06:50 UTC, naturetime10 commented on src/components/internal/InlineTask.module.scss
> +
```suggestion
```

2022-09-23 06:50 UTC, naturetime10 commented on src/components/internal/InlineTask.module.scss
> +        float: right;
Why not use `position: absolute` and set parent position to `position: relative`?

2022-09-23 06:50 UTC, naturetime10 commented on src/components/internal/InlineTask.module.scss
> +        .LeftSection {
```suggestion
        border: 2px solid transparent;
        &.Dragging {
            border: 2px solid $draggingColor;
        }
        
        .LeftSection {
```

2022-09-23 06:50 UTC, naturetime10 commented on src/components/internal/InlineTask.tsx
> +                        this.props.task.draggingBy ? styles.TaskDragging : ''
```suggestion
                    className={`${styles.Task} ${
                        this.props.task.draggingBy ? styles.Dragging : ''
```

2022-09-23 06:50 UTC, naturetime10 commented on src/components/internal/InlineTask.module.scss
> +    }
```suggestion
```

2022-09-23 06:50 UTC, naturetime10 commented on src/components/internal/InlineTask.tsx
> +                      {this.props.task.draggingBy.firstName} {this.props.task.draggingBy.lastName} is dragging
Full name maybe too long. Let's use this helper function `getUserShortName`

2022-09-23 06:50 UTC, naturetime10 commented on src/libs/dragAndDrop/DragAndDropController.ts
> +    srcContainId: string;
```suggestion
    srcContainId: string;
    target: DragTarget;
```

2022-09-23 06:50 UTC, naturetime10 commented on src/libs/dragAndDrop/DragAndDropController.ts
> +        this.dragAndDropEventChan.put({ type: 'DragEnd', target:  this.draggedTarget, srcContainId: this.sourceContainerId});
```suggestion
        this.dragAndDropEventChan.put({ 
            type: 'DragEnd', 
            srcContainId: this.sourceContainerId;
            target:  this.draggedTarget, 
        });
```

2022-09-23 06:50 UTC, naturetime10 commented on src/components/App.component.tsx
> +                    sectionIds.includes(event.srcContainId) &&
Is this line needed?

2022-09-23 06:50 UTC, naturetime10 commented on src/libs/dragAndDrop/DragAndDropController.ts
> -        this.draggedTarget = undefined;
I remember this included to fix a bug. Does the code still work if we remove them?

2022-09-23 06:50 UTC, naturetime10 commented on src/libs/network/WebSocket.HTTP.client.ts
> +}
This class should be renamed to `StateSyncClient` and moved to `storage/syncer`. This API is specific to Teamy real time state synchronization and has nothing to do with generic WebSocket.

2022-09-23 06:50 UTC, naturetime10 commented on src/libs/network/WithIdentity.ts
> +        debugger
```suggestion
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/graph/task.node.ts
> +        const taskActivity = taskActivities.find(({taskId, dragTaskActivity: {draggingClientId, isDragging} }) => {
```suggestion
        const taskActivity = taskActivities.find(({
            taskId, 
            dragTaskActivity: {
                draggingClientId, 
                isDragging
            }}) => {
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/graph/task.node.ts
> +            return isDragging && taskId === this.id && draggingClientId !== currentState.clientId
```suggestion
            return taskId === this.id && isDragging
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/graph/task.node.ts
> +    public get draggingBy(): User | undefined {
I think we should return `Client` and `Client` has `User`. This allows to decouple data layer from rendering and allow the UI to decide what to show when client ID match the current client.

2022-09-23 06:50 UTC, naturetime10 commented on src/libs/dragAndDrop/DragAndDropController.ts
> +    | TurnOffDragging
Need to discuss the changes in this class during the call

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/states/taskActivity.state.ts
> +            json.dragTaskActivity
```suggestion
             DragTaskActivity.fromJson(json.dragTaskActivity)
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/metadata.ts
> +
```suggestion
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/message.ts
> +}
Let's mirror `message` data structure as what we have at the backend.

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +            break
```suggestion
            }
            
            break;
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +    public sendClientIsReady() {
```suggestion
    public notifyInitialStateReady() {
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +        return this.webSocketHttpClient.sendClientIsReady(appState.clientId)
```suggestion
        return this.webSocketHttpClient.notifyInitialStateReady(appState.clientId)
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +    public async setInitialStateReceived() {
```suggestion
    public async setInitialStateReady() {
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +        this.initialStateReceived = true
```suggestion
        this.initialStateReady = true
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +    public onMutationReceived(): PopChannel<MessageEvent | undefined> {
```suggestion
    public onMessageReceived(): PopChannel<MessageEvent | undefined> {
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +                const messageEvent = Message.fromMutationPayload(json);
```suggestion
                const messageEvent = Message.parse(json);
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +                console.log('Mutation received: ', messageEvent);
```suggestion
                console.log('Message received: ', messageEvent);
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +                }
Switch case on message type.

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +    private readonly onMutationReceivedCh = chan<MessageEvent>();
```suggestion
    private readonly onMutationReceivedCh = chan<Mutation>();
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +                this.onMutationReceivedCh.put(messageEvent);
Skip if message type is metadata.

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +        if (remoteTeam.taskActivities.length) {
```suggestion
        if (remoteTeam.taskActivities.length > 0) {
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +                    Number(dragTaskActivity.draggingClientId),
Well written! We should change all `parseInt` to `Number()` in the following PR: https://thisthat.dev/number-constructor-vs-parse-int/

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +            return Promise.resolve('');
```suggestion
            return;
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +        return this.taskClient.startDraggingTask(
```suggestion
        }
        
        return this.taskClient.startDraggingTask(
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +    public async startDraggingTask(taskId: number): Promise<string> {
```suggestion
    public async startDraggingTask(taskId: number): Promise<string | undefined> {
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +    public async stopDraggingTask(taskId: number): Promise<string> {
```suggestion
    public async stopDraggingTask(taskId: number): Promise<string | undefined> {
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +        return this.taskClient.stopDraggingTask(
```suggestion
        if (!appState.clientId) {
            return;
        }
        
        return this.taskClient.stopDraggingTask(
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +        if (appState.clientId === undefined) {
```suggestion
        if (!appState.clientId) {
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +    private async changeMetadataState(metadata: Metadata) {
```suggestion
    private async updateClientMetadata(metadata: Metadata) {
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +    private clientIdReceived: boolean = false;
```suggestion
```

2022-09-23 06:50 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +        this.clientIdReceived = true
```suggestion
```

2022-09-23 23:38 UTC, duanxianbo commented on src/components/App.component.tsx
> +                    sectionIds.includes(event.srcContainId) &&
no

2022-09-23 23:42 UTC, naturetime10 commented on src/components/App.component.tsx
> +                    sectionIds.includes(event.srcContainId) &&
Can we remove if not needed?

2022-09-23 23:42 UTC, duanxianbo commented on src/storage/graph/task.node.ts
> +            return isDragging && taskId === this.id && draggingClientId !== currentState.clientId
why do not we check the clilent id ?

2022-09-23 23:50 UTC, duanxianbo commented on src/storage/graph/task.node.ts
> +            return isDragging && taskId === this.id && draggingClientId !== currentState.clientId
why we donot check clientid?

2022-09-23 23:51 UTC, duanxianbo commented on src/storage/syncer/stateSyncer.ts
> +    private clientIdReceived: boolean = false;
we donot check clientid recevied ?

2022-09-24 00:48 UTC, duanxianbo commented on src/libs/network/WebSocket.HTTP.client.ts
> +        private readonly httpClientWithIdentity: WithIdentity,
use httpclient

2022-09-24 00:58 UTC, duanxianbo commented on src/storage/syncer/stateSyncer.ts
> +        if (!this.clientIdReceived || !this.initialStateReceived || !appState.clientId) {
metadataReceived

2022-09-24 01:02 UTC, duanxianbo commented on src/storage/syncer/stateSyncer.ts
> +        private withIdentity: WithIdentity,
remove private and change to httpClient

2022-09-24 01:06 UTC, duanxianbo commented on src/storage/syncer/stateSyncer.ts
> +                const messageEvent = Message.fromMutationPayload(json);
Discussed offline, feedback is outdated and will drop

2022-09-24 01:09 UTC, duanxianbo commented on src/storage/syncer/stateSyncer.ts
> +                this.onMutationReceivedCh.put(messageEvent);
check if metadata is received

2022-09-25 06:46 UTC, naturetime10 requested changes

2022-09-25 06:46 UTC, naturetime10 commented on src/components/App.component.tsx
> +                                                    currentClientId={this.state.currentClientId}
Backlog has reference to`localStore`. I think you can get client ID inside of it.

2022-09-25 06:46 UTC, naturetime10 commented on src/components/App.component.tsx
> +                                                    currentClientId={
Sprints has reference to `localStore`. I think you can get client ID inside of it.

2022-09-25 06:46 UTC, naturetime10 commented on src/components/App.component.tsx
> +                this.setState({currentClientId: appState.clientId})
```suggestion
```

2022-09-25 06:46 UTC, naturetime10 commented on src/components/App.component.tsx
> +    currentClientId?: number;
```suggestion
```

2022-09-25 06:46 UTC, naturetime10 commented on src/components/App.component.tsx
> +                await this.stateSyncer.setInitialStateReceived();
```suggestion
                await this.stateSyncer.notifyInitialStateReceived();
```

2022-09-25 06:46 UTC, naturetime10 commented on src/components/internal/Backlog.component.tsx
> +    currentClientId?: number;
```suggestion
```

2022-09-25 06:46 UTC, naturetime10 commented on src/components/internal/InlineTask.module.scss
> +        &.Dragging {
```suggestion
        border: 2px solid transparent;
        
        &.Dragging {
```

2022-09-25 06:46 UTC, naturetime10 commented on src/components/internal/InlineTask.tsx
> +                        this.props.task.draggingBy ? styles.Dragging : ''
```suggestion
                        classnames({
                            [styles.Dragging]: this.props.task.draggingBy 
                        })
```

2022-09-25 06:46 UTC, naturetime10 commented on src/components/internal/InlineTask.tsx
> +                {this.props.task.draggingBy && this.props.task.draggingBy.clientId !== this.props.currentClientId && (
Add `const {draggingBy} = this.props.task;` before linee 75.

2022-09-25 06:46 UTC, naturetime10 commented on src/dep/deps.ts
> +    const httpClient = new FetchHTTPClient()
```suggestion
    let httpClient = new FetchHTTPClient();
    httpClient = new WithIdentity(httpClient);
```

2022-09-25 06:46 UTC, naturetime10 commented on src/dep/deps.ts
> +    const httpClientWithIdentity = new WithIdentity(httpClient);
```suggestion
```

2022-09-25 06:46 UTC, naturetime10 commented on src/entity/client.ts
> +    user: UserNode
```suggestion
    user: User
```

2022-09-25 06:46 UTC, naturetime10 commented on src/entity/client.ts
> +    user: UserNode
Nodes are only valid in the context of `Graph` but not generic data model.

2022-09-25 06:46 UTC, naturetime10 commented on src/entity/client.ts
> +    clientId: number;
```suggestion
    id: number;
```

2022-09-25 06:46 UTC, naturetime10 commented on src/storage/graph/task.node.ts
> +        }
Please create ClientNode instead.

2022-09-25 06:46 UTC, naturetime10 commented on src/storage/syncer/message.ts
> +}
```suggestion
export type MessageType = 'Mutation' | 'Metadata';
```

2022-09-25 06:46 UTC, naturetime10 commented on src/storage/syncer/stateSyncClient.ts
> +        this.withIdentityHttpClient = new WithIdentity(this.httpClient)
```suggestion
```

2022-09-25 06:46 UTC, naturetime10 commented on src/storage/syncer/stateSyncClient.ts
> +        return this.withIdentityHttpClient.request(
```suggestion
        return this.httpClient.request(
```

2022-09-25 06:46 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +
```suggestion
```

2022-09-25 06:46 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +    private readonly stateSyncClient;
```suggestion
    private readonly stateSyncClient: StateSyncClient;
```

2022-09-25 06:46 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +        httpClient: HTTPClient,
```suggestion
        private stateSyncClient: StateSyncClient,
```

2022-09-25 06:46 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +        );
```suggestion
```

2022-09-25 06:46 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +    public onMessageReceived(): PopChannel<Mutation | undefined> {
```suggestion
    public onMutationReceived(): PopChannel<Mutation | undefined> {
```

2022-09-25 06:46 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +                    resolve(null);
```suggestion
                    resolve();
```

2022-09-25 06:46 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
>                  const messageEvent = Message.fromMutationPayload(json);
```suggestion
                const message = Message.fromMutationPayload(json);
```

2022-09-25 06:46 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +                        resolve(null);
```suggestion
                        resolve();
```

2022-09-25 06:46 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +                        const mutation = Mutation.fromMutationPayload(messageEvent.payload)
Don't mutate state if metadata not received yet

2022-09-25 06:46 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +        appState = this.localStore.getState();
```suggestion

        appState = this.localStore.getState();
```

2022-09-25 06:47 UTC, naturetime10 commented
Can we show `Xianbo D. is dragging`? Only showing the name is confusing to user.

2022-09-25 16:33 UTC, duanxianbo commented on src/storage/syncer/stateSyncer.ts
> +                    resolve(null);
will apply this, but I do not think it will build,since resolve always needs a param

2022-09-26 03:21 UTC, naturetime10 requested changes

2022-09-26 03:21 UTC, naturetime10 commented on src/components/internal/InlineTask.tsx
> +                            [styles.Dragging]: draggingBy
```suggestion
                            [styles.Dragging]: draggingBy !== undefined
```

2022-09-26 03:21 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +
```suggestion
```

2022-09-26 03:21 UTC, naturetime10 commented on src/storage/graph/client.node.ts
> +    constructor(private clientId: number, private userNode: UserNode) {}
```suggestion
    constructor(private localStore: LocalStore, private clientState: ClientState) {}
```

2022-09-26 23:55 UTC, duanxianbo commented on src/storage/graph/client.node.ts
> +    constructor(private clientId: number, private userNode: UserNode) {}
what is deps used for here?

2022-09-27 00:39 UTC, naturetime10 commented on src/storage/graph/client.node.ts
> +    constructor(private clientId: number, private userNode: UserNode) {}
You need it to query user based on user ID

2022-09-27 00:40 UTC, naturetime10 commented on src/storage/graph/client.node.ts
> +    constructor(private clientId: number, private userNode: UserNode) {}
Sorry, I meant localStore.

2022-09-28 01:41 UTC, naturetime10 requested changes

2022-09-28 01:41 UTC, naturetime10 commented on src/client/team.client.ts
> +                                            id
```suggestion
                                            id
                                            firstName
                                            lastName
```

2022-09-28 01:41 UTC, naturetime10 commented on src/client/team.client.ts
> +                                            id
I thought we wanted to show user's first name and last name

2022-09-28 01:41 UTC, naturetime10 commented on src/storage/states/client.state.ts
> +            json.user.id,
```suggestion
            json.userId,
```

We are currently calling this when deserializing from `localStorage` and not from GraphQL

2022-09-28 01:41 UTC, naturetime10 commented on src/storage/states/taskActivity.state.ts
> +             DragTaskActivityState.fromJson(json.dragTaskActivity)
```suggestion
            DragTaskActivityState.fromJson(json.dragTaskActivity)
```

2022-09-28 01:41 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +        if (!!remoteTeam.taskActivities?.length) {
```suggestion
        if (remoteTeam.taskActivities?.length) {
```

2022-09-28 01:41 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +            const clientState = ClientState.fromJson(taskActivity.dragTaskActivity.client)
We are not using fromJson here. Let's manually initialize client and merge it with existing client.

2022-09-28 01:41 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +            const clientState = ClientState.fromJson(taskActivity.dragTaskActivity.client)
We will create `fromRemoteClient` helper in the future.

2022-09-28 01:56 UTC, duanxianbo commented on src/client/team.client.ts
> +                                            id
I am thinking we we are getting the user node from the users map in the client

2022-09-28 02:35 UTC, naturetime10 requested changes

2022-09-28 02:35 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +            const clientState = ClientState.fromJson(taskActivity.dragTaskActivity.client)
Let's not use `ClientState.fromJson` and call constructor directly.

2022-09-29 01:54 UTC, duanxianbo commented on src/client/team.client.ts
> +                                            id
merged with local user

2022-09-29 01:54 UTC, duanxianbo commented on src/storage/syncer/stateSyncer.ts
> +            const clientState = ClientState.fromJson(taskActivity.dragTaskActivity.client)
done

2022-09-29 05:27 UTC, naturetime10 requested changes

2022-09-29 05:27 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +                const clientState = ClientState.fromMutationPayload(mutation.payload.DragTaskActivity.Client)
I thought we are going to `mergeClient` with existing client info instead of completely replace client who has only partial data.

2022-09-29 05:27 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +            const taskActivityIndex = currState.taskActivities.findIndex(({taskId}) => taskId === updatedTaskActivity.taskId)
```suggestion
            }
            
            const taskActivityIndex = currState.taskActivities.findIndex(({taskId}) => taskId === updatedTaskActivity.taskId)
```

2022-09-29 05:27 UTC, naturetime10 commented on src/storage/states/app.state.ts
> +        public taskActivities: TaskActivityState[],
Should we index task activities with `taskID` for fast lookup?

2022-09-29 05:27 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +        return this.stateSyncClient.sendClientIsReady(appState.clientId);
```suggestion
        return this.stateSyncClient.sendInitialStateIsReady(appState.clientId);
```

2022-09-29 20:07 UTC, duanxianbo commented on src/storage/states/app.state.ts
> +        public taskActivities: TaskActivityState[],
yes, that would be a good idea

2022-09-30 15:41 UTC, duanxianbo commented on src/storage/syncer/stateMutators.ts
> +                const clientState = ClientState.fromMutationPayload(mutation.payload.DragTaskActivity.Client)
done

2022-10-01 01:04 UTC, naturetime10 requested changes

2022-10-01 01:04 UTC, naturetime10 commented on src/storage/graph/task.node.ts
> +        if (!taskActivity?.dragTaskActivity.clientId || !taskActivity.dragTaskActivity.isDragging) {
```suggestion
        if (!taskActivity.dragTaskActivity.isDragging || !taskActivity?.dragTaskActivity.clientId) {
```

2022-10-01 01:04 UTC, naturetime10 commented on src/storage/states/app.state.ts
> +        public clientId?: number
```suggestion
        public currClientId?: number
```

2022-10-01 01:04 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +
```suggestion
```

2022-10-01 01:04 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +
```suggestion
```

2022-10-01 01:04 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +                }
Use new

2022-10-01 01:04 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +
```suggestion
```

2022-10-01 02:48 UTC, naturetime10 approved these changes

2022-10-01 02:51 UTC, merged