Use httpclient for graphql
teamyapp/teamy-web pull request #378
Opened 2022-10-08 15:09 UTC by duanxianbo

2022-10-08 17:32 UTC, naturetime10 requested changes

2022-10-08 17:32 UTC, naturetime10 commented on src/client/invitation.client.ts
> +                query: `
```suggestion
                mutation: `
```

2022-10-08 17:32 UTC, naturetime10 commented on src/client/invitation.client.ts
> +                operationName: "getInvitations",
Can this be optional?

2022-10-08 17:32 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +    debugger
```suggestion
```

2022-10-09 16:11 UTC, duanxianbo commented on src/client/invitation.client.ts
> +                operationName: "getInvitations",
yep

2022-10-09 17:01 UTC, naturetime10 approved these changes

2022-10-09 17:01 UTC, merged