Add expoential backoff retry
teamyapp/teamy-web pull request #379
Opened 2022-10-09 21:08 UTC by duanxianbo

2022-10-09 21:11 UTC, duanxianbo commented on src/libs/network/middleware/clientHTTPWithExponentialRetry.ts
> +
```suggestion
```

2022-10-09 21:11 UTC, duanxianbo commented on src/libs/network/middleware/clientHTTPWithExponentialRetry.ts
> +
```suggestion
```

2022-10-21 01:51 UTC, naturetime10 requested changes
Use csp to pause / resume wait in Mock clock.

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithExponentialRetry.ts
> +const backoff = new ExponentialBuilder().build()
```suggestion
const backoff = new ExponentialBackoffBuilder().build()
```

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithExponentialRetry.ts
> +export function clientHTTPWithExponentialRetry(
```suggestion
export function clientHTTPWithRetry(
```

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithExponentialRetry.ts
> +
```suggestion
Declare retry class here.
```

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithExponentialRetry.ts
> +    maxRetries: number = 10,
```suggestion
```

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithExponentialRetry.ts
> +                    while (currentRetry < maxRetries) {
Use maxCount retry library.

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithExponentialRetry.ts
> +    maxRetries: number = 10,
retry: Retry

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/retry/backoff/exponential.ts
> +
```suggestion
```

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/retry/backoff/exponential.ts
> +        this.nextDelay = Math.min(scaled + this.randOffset(), this.maxDelay);
```suggestion
        this.nextDelay = Math.min(scaled, this.maxDelay) + this.randOffset();
```

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/retry/backoff/exponential.ts
> +}
Change to options pattern. Define `Options` interface and pass into constructor

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/retry/backoff/index.ts
> +	delay: () => number
```suggestion
	delay: () => Duration
```

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/retry/clock.ts
> +
```suggestion
```

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/retry/infinite.ts
> +
```suggestion
```

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/retry/maxCount.ts
> +
```suggestion
```

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/retry/maxCount.ts
> +
```suggestion
```

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/retry/maxCount.ts
> +
```suggestion
```

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/retry/timeout.ts
> +                if (this.clock.now().getTime() >= expiredAt) {
```suggestion
                this.backoff.onFailure();
                if (this.clock.now().getTime() + this.backoff.delay() >= expiredAt) {
```

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/retry/timeout.ts
> +                await this.clock.wait(this.backoff.delay())
```suggestion
```

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/retry/timeout.ts
> +
```suggestion
```

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/retry/timeout.ts
> +
```suggestion
```

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/retry/backoff/index.ts
> +export interface BackOff {
rename file to `backoff.ts`

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/retry/backoff/exponential.ts
> +export class Exponential implements BackOff {
```suggestion
export class ExponentialBackoff implements Backoff {
```

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/retry/tests/retry.test.ts
> +            })
Move backoff related tests to backoff package.

2022-10-21 01:51 UTC, naturetime10 commented on src/libs/retry/tests/retry.test.ts
> +import { notStrictEqual, strictEqual } from 'assert';
Simple test to confirm the interfaces are not broken

2022-10-23 01:24 UTC, duanxianbo commented on src/libs/retry/backoff/index.ts
> +	delay: () => number
you mean  the duration from `src\entity\duration.ts` ?? if we really want to use it , should we move it from entity folder  to lib folder

2022-10-30 09:57 UTC, naturetime10 requested changes

2022-10-30 09:57 UTC, naturetime10 commented on src/libs/math/randomNumberGenerator.ts
> +        const num = this.randomFloats[this.nextRandomFloatIndex];
```suggestion
        if (this.nextRandomFloatIndex === this.randomFloats.length) {
            this.nextRandomFloatIndex = 0;
        }
        
        const num = this.randomFloats[this.nextRandomFloatIndex];
```

2022-10-30 09:57 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithRetry.ts
> +
Can we inline this into line 28?

2022-10-30 09:57 UTC, naturetime10 commented on src/libs/retry/backoff/exponential.test.ts
> +    it('should create default exponential', () => {
```suggestion
    const testRandGen = new TestRandomNumberGenerator();
    
    it('should create default exponential backoff', () => {
```

2022-10-30 09:57 UTC, naturetime10 commented on src/libs/retry/backoff/exponential.test.ts
> +        const exponential = new Exponential(testRandGen);
```suggestion
        const exponentialBackoff = new ExponentialBackoff(testRandGen);
```

2022-10-30 09:57 UTC, naturetime10 commented on src/libs/retry/backoff/exponential.test.ts
> +        it('should add next delay after failure', () => {
```suggestion
        });
        
        it('should add next delay after failure', () => {
```

2022-10-30 09:57 UTC, naturetime10 commented on src/libs/retry/backoff/exponential.test.ts
> +        });
```suggestion
        });
```

2022-10-30 09:57 UTC, naturetime10 commented on src/libs/retry/backoff/exponential.test.ts
> +        strictEqual(exponential.delay().totalMilliSeconds, 4);
I think we need to fail as few times before succeeding to confirm this. This test is ambiguous with succeeding not less than minDelay.

2022-10-30 09:57 UTC, naturetime10 commented on src/libs/retry/backoff/exponential.ts
> +    nextDelay: number;
```suggestion
```
Next delay is internal state and is not not an option.

2022-10-30 09:57 UTC, naturetime10 commented on src/libs/retry/backoff/exponential.ts
> +        };
We should read individual private field from options instead of saving the options all together.

2022-10-30 09:57 UTC, naturetime10 commented on src/libs/retry/backoff/exponential.ts
> +
```suggestion
```

2022-10-30 21:14 UTC, naturetime10 requested changes

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/network/FetchHTTP.client.ts
> +
```suggestion
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithRetry.ts
> +                    new Promise<Error | undefined>(async (_resolve) => {
```suggestion
                    new Promise<InternalError | undefined>(async (resolve) => {
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/error/errors.ts
> +export class CustomError extends Error {
```suggestion
export class InternalError extends Error {
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/infinite.test.ts
> +    it('should call execute until max time', async () => {
```suggestion
    it('retry until succeeded', async () => {
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/infinite.test.ts
> +        for (let time = 1; time <= 10; time++) {
```suggestion
        for (let retry = 1; time <= 10; time++) {
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/infinite.ts
> +export class Infinite implements Retry {
```suggestion
export class InfiniteRetry implements Retry {
```

TypeScript won't automatically prefix package name in front of class name. To make our classes more clear, let's name it to InfiniteRetry

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/infinite.test.ts
> +
```suggestion
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/maxCount.test.ts
> +    it('should get result before reaching max count', async () => {
```suggestion
    it('should succeed before reaching max count', async () => {
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/maxCount.test.ts
> +            strictEqual(duration.totalMilliSeconds, 16)
```suggestion
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/maxCount.test.ts
> +        strictEqual(duration.totalMilliSeconds, 16)
```suggestion
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/maxCount.test.ts
> +        strictEqual(duration.totalMilliSeconds, 4)
```suggestion
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/maxCount.test.ts
> +        strictEqual(duration.totalMilliSeconds, 16)
Let's not check time here.

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/maxCount.ts
> +        execute: () => Promise<Error | undefined>,
```suggestion
        execute: () => Promise<InternalError | undefined>,
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/retry.test.ts
> +    execute: () => Promise<undefined | Error>;
```suggestion
    execute: () => Promise<InternalError | undefined>;
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/retry.test.ts
> +        });
You can use 2 arrays and do 2 for loops for testing since the interfaces should always match. I recommend we do check the retry count and execute state though.

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/retry.ts
> +    ) => Promise<[number, Error | undefined]>;
```suggestion
    ) => Promise<[number, InternalError | undefined]>;
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/retry.ts
> +        execute: () => Promise<Error | undefined>,
```suggestion
        execute: () => Promise<InternalError | undefined>,
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/timeout.test.ts
> +            }
Can we assign this function to a separate variable? I didn't see it's using any of executable's internal state.

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/timeout.test.ts
> +    it('should get result in time', async () => {
```suggestion
    it('should succeed before timeout', async () => {
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/timeout.test.ts
> +            strictEqual(duration.totalMilliSeconds, 16)
```suggestion
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/timeout.test.ts
> +        strictEqual(duration.totalMilliSeconds, 4)
```suggestion
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/timeout.test.ts
> +        strictEqual(duration.totalMilliSeconds, 16)
```suggestion
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/timeout.test.ts
> +    it('should throw error if not getting result in time', async () => {
```suggestion
    it('should get error when reaching timeout', async () => {
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/timeout.test.ts
> +            strictEqual(duration.totalMilliSeconds, 4)
```suggestion
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/timeout.test.ts
> +        strictEqual(duration.totalMilliSeconds, 4)
```suggestion
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/timeout.ts
> +        execute: () => Promise<Error | undefined>,
```suggestion
        execute: () => Promise<InternalError | undefined>,
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/timeout.ts
> +    ): Promise<[number, Error | undefined]> {
```suggestion
    ): Promise<[number, InternalError | undefined]> {
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/timeout.ts
> +        let err: Error | undefined;
```suggestion
        let err: InternalError | undefined;
```

2022-10-30 21:14 UTC, naturetime10 commented on src/libs/retry/timeout.ts
> +        let err: Error | undefined;
Can those variables be defined inside the promise?

2022-10-31 01:57 UTC, duanxianbo commented on src/libs/retry/retry.test.ts
> +        });
but the retry count and execute state are tested in other test suite? (ex: timeout.test.ts)

2022-10-31 02:00 UTC, duanxianbo commented on src/libs/network/middleware/clientHTTPWithRetry.ts
> +
done

2022-10-31 02:00 UTC, duanxianbo commented on src/libs/retry/backoff/exponential.test.ts
> +        strictEqual(exponential.delay().totalMilliSeconds, 4);
done

2022-10-31 02:00 UTC, duanxianbo commented on src/libs/retry/backoff/exponential.ts
> +        };
yes

2022-10-31 02:00 UTC, naturetime10 commented on src/libs/retry/retry.test.ts
> +        });
This is more for general integration

2022-10-31 02:00 UTC, duanxianbo commented on src/libs/retry/timeout.test.ts
> +            }
yes

2022-10-31 02:01 UTC, naturetime10 commented on src/libs/retry/retry.test.ts
> +        });
No need too much detailed assertion. Just make sure each combination seems good.

2022-10-31 02:01 UTC, naturetime10 commented on src/libs/retry/retry.test.ts
> +        });
Or we don't need this test.

2022-10-31 02:02 UTC, duanxianbo commented on src/libs/retry/timeout.ts
> +        let err: Error | undefined;
yes

2022-11-01 00:15 UTC, naturetime10 requested changes

2022-11-01 00:15 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithRetry.ts
> +
```suggestion
```

2022-11-01 00:15 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithRetry.ts
> +
```suggestion
```

2022-11-01 00:15 UTC, naturetime10 commented on src/libs/retry/infinite.test.ts
> +describe('Infinite', () => {
```suggestion
describe('InfiniteRetry', () => {
```

2022-11-01 00:15 UTC, naturetime10 approved these changes

2022-11-01 00:25 UTC, merged