Sort teams by name
teamyapp/teamy-web pull request #382
Opened 2022-10-10 20:31 UTC by duanxianbo

2022-10-11 00:48 UTC, naturetime10 requested changes

2022-10-11 00:48 UTC, naturetime10 commented on src/components/internal/Drawer.tsx
> +
Let's extra this to a common helper and put it inside `src/data/task.order.ts`

2022-10-15 02:16 UTC, naturetime10 requested changes

2022-10-15 02:16 UTC, naturetime10 commented on src/data/team.order.ts
> +
```suggestion
```

2022-10-15 02:16 UTC, duanxianbo commented on src/data/team.order.ts
> +
```suggestion

```

2022-10-15 02:17 UTC, naturetime10 approved these changes

2022-10-15 02:19 UTC, merged