Send client logs proto
teamyapp/teamy-web pull request #388
Opened 2022-10-16 02:38 UTC by duanxianbo

2022-10-18 01:25 UTC, duanxianbo commented on src/libs/telemetry/Logger.ts
> +
```suggestion
```

2022-10-27 07:41 UTC, naturetime10 commented on src/dep/deps.ts
> +    const obsClient = new ObsClient(`${config.cloudWebAPIEndpoint}/monitor`, httpClient)
```suggestion
    const telemetryClient = new TelemetryClient(`${config.cloudWebAPIEndpoint}`, httpClient)
```

2022-10-28 01:19 UTC, duanxianbo commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                    url: string,
pass in context to http request

2022-10-28 01:23 UTC, duanxianbo commented on src/libs/telemetry/middleware/logWithContext.ts
> +};
change to log with id, and add a new middleware to add service name

2022-10-28 01:23 UTC, duanxianbo commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                },
middleware to add serviceName: teamy-web-browser

2022-10-28 01:29 UTC, duanxianbo commented on src/libs/telemetry/RawLogger.ts
> +const duration = 2000
use entity/Duration pass string format "T2S"

2022-10-31 01:54 UTC, naturetime10 requested changes

2022-10-31 01:54 UTC, naturetime10 commented on src/dep/deps.ts
> +import { ObsClient } from '@lib/telemetry/ObsClient';
```suggestion
import { TelemetryClient } from '@lib/telemetry/TelemetryClient';
```

2022-10-31 01:54 UTC, naturetime10 commented on src/dep/deps.ts
> +    const logger = WithMiddlewares<Logger>(new RawLogger("Info", obsClient), [
Can get log level from `config`?

2022-10-31 01:54 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +
```suggestion
```

2022-10-31 01:54 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                    }
```suggestion
```

2022-10-31 01:54 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                    })
Log the request header, request body, response header and response body so that request information can be uploaded to datadog for analysis.

2022-10-31 01:54 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +
```suggestion
```

2022-10-31 01:54 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                    })
```
logger.logWithContext(context,  "Info", {
    [Prop.FileName]: 'COMPILE_TIME_INJECT_FILENAME',
    [Prop.LineNumber]: 'COMPILE_TIME_INJECT_LINE_NUMBER'
})
```

Pass in `COMPILE_TIME_INJECT_FILENAME` and `COMPILE_TIME_INJECT_LINE_NUMBER` so that our build time plugin can replace them with the correct file name and line number.

2022-10-31 01:54 UTC, naturetime10 commented on src/libs/telemetry/LogLevel.ts
> +export type LogLevel = "Off" | "Fatal" |"Error"|"Warning"|"Info"| "Debug"
Use single quote everywhere when possible. Remove empty lines.

2022-10-31 01:54 UTC, naturetime10 commented on src/libs/telemetry/Logger.ts
> +
Remove empty lines.

2022-10-31 01:54 UTC, naturetime10 commented on src/libs/telemetry/ObsClient.ts
> +            `${this.connectionUrl}/monitor/upload-log`,
```suggestion
            `${this.connectionUrl}/telemetry/upload-log`,
```

Let's change monitoring to `telemetry` also at backend.

2022-10-31 01:54 UTC, naturetime10 commented on src/libs/telemetry/ObsClient.ts
> +        private readonly connectionUrl: string,
```suggestion
        private readonly telemetryApiEndpoint: string,
```

2022-10-31 01:54 UTC, naturetime10 commented on src/libs/telemetry/Props.ts
> +}
Do `type Prop = 'Cause' | 'Message'` so that we can receive reable enums from backend for better debugging.

2022-10-31 01:54 UTC, naturetime10 commented on src/libs/telemetry/RawLogger.ts
> +const duration = 2000
Let’s call it `LOG_UPLOAD_INTERVAL`.

2022-10-31 01:54 UTC, naturetime10 commented on src/libs/telemetry/RawLogger.ts
> +const wait = (duration: number) => new Promise((resolve) => setTimeout(resolve, duration))
Use wait in clock which will be checked through retry PR.

2022-10-31 01:54 UTC, naturetime10 commented on src/libs/telemetry/Logger.ts
> +
```suggestion
```

2022-10-31 01:54 UTC, naturetime10 commented on src/libs/telemetry/LogLevel.ts
> +export const LogLevelRank: Record<LogLevel, number> = {
```suggestion
export const LOG_LEVEL_RANKS: Record<LogLevel, number> = {
```

2022-11-02 00:49 UTC, naturetime10 requested changes

2022-11-02 00:49 UTC, naturetime10 commented on src/dep/deps.ts
> +
```suggestion
```

2022-11-02 00:49 UTC, naturetime10 commented on src/dep/deps.ts
> +        logWithRequestId, logWithServiceName
Can we put middlewares in seperate lines?

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/network/HTTP.client.ts
> +    serviceName?: string
Can we pass in map instead so that any kinds of key values pairs can be passed in through middleware?

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithIdentity.ts
> +            context = {}
```suggestion
            context? = {}
```

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/network/HTTP.client.ts
> +
```suggestion
```

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                context: Context = {},
```suggestion
                context?: Context = {},
```

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                    Method: options?.method || "get",
```suggestion
                    Method: options?.method || "Get",
```

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                const [res, headers, error] = await httpClient.request(url, options, context);
```suggestion
                const [res, resHeaders, error] = await httpClient.request(url, options, context);
```

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                    Method: options?.method || "get",
```suggestion
                    Method: options?.method || 'Get',
```

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +
```suggestion
```

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithRequestId.ts
> +            context: Context = {}
```suggestion
            context?: Context = {}
```

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithRetry.ts
> +                context = {}
```suggestion
                context? = {}
```

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/telemetry/LogLevel.ts
> +
```suggestion
```

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/telemetry/LogLevel.ts
> +export type LogLevel = 'Off' | 'Fatal' | 'Error' | 'Warning' | 'Info' | 'Debug'
```suggestion
export type LogLevel = 'Off' | 'Fatal' | 'Error' | 'Warning' | 'Info' | 'Debug';
```

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/telemetry/Logger.ts
> +}
Can this be a generic map?

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/telemetry/Props.ts
> +    | 'RequestId';
We need to make PropName a string to allow easy customization through custom middleware.

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/telemetry/Props.ts
> +export type Props = PartialRecord<Prop, any>;
```suggestion
export type Props = PartialRecord<string, any>;
```

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/telemetry/RawLogger.ts
> +    private runtime = new BuiltInRuntime()
We do pass it in through constructor to conform `Dependency injection` for easier testing in the future.

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/telemetry/RawLogger.ts
> +        this.logWithContextAndSkip(ct, level, props);
I wonder why do we need to pass in skip? It's only needed in Go to instruct the runtime to log correct file name where log is printed.

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/telemetry/RawLogger.ts
> +    public logAndSkip(level: LogLevel, properties: Props) {
```suggestion
```

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/telemetry/RawLogger.ts
> +    }
```suggestion
```

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/telemetry/middleware/logWithServiceName.ts
> +            logger.logWithContext(context, level, {...props, ServiceName: 'teamy-web-browser'})
Service name should be passed into `logWithServiceName`. We are building a generic library which could be used by others in the future.

2022-11-02 00:49 UTC, naturetime10 commented on src/libs/types.d.ts
> +  };
```suggestion
```

2022-11-03 00:42 UTC, duanxianbo commented on src/libs/network/middleware/clientHTTPWithIdentity.ts
> +            context = {}
typescript will not let us do so

2022-11-05 00:33 UTC, naturetime10 requested changes

2022-11-05 00:33 UTC, naturetime10 commented on src/dep/deps.ts
> +                10,
Can this be from config or constant?

2022-11-05 00:33 UTC, naturetime10 commented on src/dep/deps.ts
> +
```suggestion
```

2022-11-05 00:33 UTC, naturetime10 commented on src/libs/error/result.ts
> +export type Result<Value, Error> = [Value | null, Response['headers'] | null, Error | null];
Revert this change.

2022-11-05 00:33 UTC, naturetime10 commented on src/libs/identity/Identity.client.ts
> +        return result[2] === null;
Can we receive the value with a variable so that it's more readable?

2022-11-05 00:33 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                context = {},
```suggestion
                context?: Record<string, any> = {},
```

2022-11-05 00:33 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithRetry.ts
> +                    result = await httpClient.request(url, options, context);
Can we assign into readable variables?

2022-11-05 00:33 UTC, naturetime10 commented on src/libs/telemetry/Logger.ts
> +}
```suggestion
type Context Record<string, any>
```

2022-11-05 00:33 UTC, naturetime10 commented on src/libs/telemetry/Props.ts
> +    | 'RequestId';
Remove this.

2022-11-05 00:33 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +            ): Promise<Result<string, InternalError>> => {
```suggestion
            ): Promise<Result<HTTPResponse, InternalError>> => {
```

2022-11-05 00:33 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +            ): Promise<Result<string, InternalError>> => {
HTTPResponse {
    body: string
    header: Record<string, string>
    statusCode: int
}

2022-11-05 02:03 UTC, duanxianbo commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                context: Context = {},
same

2022-11-05 02:03 UTC, duanxianbo commented on src/libs/network/middleware/clientHTTPWithRequestId.ts
> +            context: Context = {}
same

2022-11-05 02:03 UTC, duanxianbo commented on src/libs/network/middleware/clientHTTPWithRetry.ts
> +                context = {}
same

2022-11-05 02:03 UTC, duanxianbo commented on src/libs/telemetry/RawLogger.ts
> +        this.logWithContextAndSkip(ct, level, props);
removed

2022-11-05 02:03 UTC, duanxianbo commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                context = {},
? can not be added since typescript will not allow that, and `Record<string, any>` type is not needed since we are implementing the the interface ` Middleware<HTTPClient>`

2022-11-05 02:21 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                context = {},
Pass in `{}` when calling `logWithContext`

2022-11-05 02:23 UTC, naturetime10 commented on src/libs/telemetry/Props.ts
> +    | 'RequestId';
Define those as string constants.

2022-11-05 02:24 UTC, naturetime10 commented on src/libs/telemetry/Props.ts
> +    | 'RequestId';
export const BODY_PROP = 'Body';

2022-11-05 20:24 UTC, duanxianbo commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                context = {},
changed context to be optional in `logWithContext `function

2022-11-09 03:56 UTC, naturetime10 requested changes

2022-11-09 03:56 UTC, naturetime10 commented on src/dep/deps.ts
> +                config.maxRetryTimes,
```suggestion
                config.maxAPIRetryTimes,
```

2022-11-09 03:56 UTC, naturetime10 commented on src/libs/network/FetchHTTP.client.ts
> +                    const header = Object.fromEntries(response.headers.entries())
```suggestion
                    const headers = Object.fromEntries(response.headers.entries())
```

2022-11-09 03:56 UTC, naturetime10 commented on src/libs/network/FetchHTTP.client.ts
> +                                header,
```suggestion
                                headers,
```

2022-11-09 03:56 UTC, naturetime10 commented on src/libs/network/FetchHTTP.client.ts
> +                                header,
```suggestion
                                headers,
```

2022-11-09 03:56 UTC, naturetime10 commented on src/libs/network/HTTP.client.ts
> +    header: Record<string, string>;
```suggestion
    headers: Record<string, string>;
```

2022-11-09 03:56 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                }, context);
Log error and info separately. Log `INFO` does not need `[CauseProp]: error`

2022-11-09 03:56 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithRequestId.ts
> +            context
Add types

2022-11-09 03:56 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                context,
Add types

2022-11-09 03:56 UTC, naturetime10 commented on src/libs/telemetry/middleware/logWithRequestId.ts
> +            logger.logWithContext(level, {...props, [RequestIdProp]: context?.requestId}, context)
Only add `RequestIdProp` when context is not `undefined`

2022-11-10 01:39 UTC, duanxianbo commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                }, context);
done

2022-11-10 01:43 UTC, duanxianbo commented on src/libs/network/middleware/clientHTTPWithLogger.ts
> +                context,
do we need to add them? they are implied by the interface https://github.com/teamyapp/teamy-web/blob/5e922ca90d175907cfdbae46c9ae6dc3aa1ff7e4/src/libs/network/HTTP.client.ts#L8

2022-11-11 01:42 UTC, naturetime10 requested changes

2022-11-11 01:42 UTC, naturetime10 commented on src/libs/network/FetchHTTP.client.ts
> +                    const headers = Object.fromEntries(response.headers.entries())
```suggestion
                    const headers = Object.fromEntries(response.headers.entries());
```

2022-11-11 01:42 UTC, naturetime10 commented on src/libs/network/HTTP.client.ts
>  export interface HTTPClient {
```suggestion
}

export interface HTTPClient {
```

2022-11-11 02:07 UTC, naturetime10 approved these changes

2022-11-11 02:07 UTC, merged