Allow user to select multi participants filters
teamyapp/teamy-web pull request #394
Opened 2022-10-27 01:43 UTC by duanxianbo

![image](https://user-images.githubusercontent.com/6356492/204700702-7daf0c2e-e7ff-4633-abac-49c519e9700a.png)

changed text when toggled, not sure if it is a good idea

2022-10-27 02:00 UTC, duanxianbo commented on src/libs/event/keyBoardEventMoniter.ts
> +
```suggestion
```

2022-10-27 02:00 UTC, duanxianbo commented on src/libs/event/keyBoardEventMoniter.ts
> +
```suggestion
```

2022-10-31 02:16 UTC, naturetime10 requested changes

2022-10-31 02:16 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +    isInMultiSelection: boolean;
```suggestion
    allowMultiSelections: boolean;
```

2022-10-31 02:16 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                const keyboardEventEle = await this.keyBoardEventChan!.pop();
```suggestion
                const keyboardEvent = await this.keyBoardEventChan!.pop();
```

2022-10-31 02:16 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +
```suggestion
```

2022-10-31 02:16 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                    event === 'keydown'
I think we should first check key down then check control.

2022-10-31 02:16 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +export interface KeyboardEventEle {
```suggestion
export interface KeyboardEventPayload {
```

2022-10-31 02:16 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +
```suggestion
```

2022-10-31 02:16 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +    private keyupListener = (event: KeyboardEvent) => {
```suggestion
    private onKeyUp = (event: KeyboardEvent) => {
```

2022-10-31 02:16 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +    private keydownListener = (event: KeyboardEvent) => {
```suggestion
    private onKeyDown = (event: KeyboardEvent) => {
```

2022-10-31 02:16 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +            event: "keyup"
```suggestion
            event: 'keyup'
```

2022-10-31 02:16 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +            event: "keydown"
```suggestion
            event: 'keydown'
```

2022-10-31 02:16 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +type KeyboardEventType = keyof Pick<DocumentEventMap, "keydown" | "keyup">
```suggestion
type KeyboardEventType = 'keydown' | 'keyup';
```

2022-10-31 02:16 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +
```suggestion
```

2022-10-31 02:16 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +    public subscribe() {
```suggestion
    public subscribe(): PopChannel<KeyboardEvenPayload | undefined>; {
```

2022-10-31 02:16 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                    event === 'keydown'
Did we handle the case when command key is released?

2022-10-31 02:16 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                                            )}
```suggestion
                                            {this.renderCheckbox(
                                                userAll,
                                            )}
```

2022-10-31 02:16 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                                            {this.checkToRenderCheckbox(
```suggestion
                                            {this.renderCheckbox(
```

2022-10-31 02:16 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +    private checkToRenderCheckbox = (userIdentity: string): ReactNode => {
```suggestion
    private renderCheckbox = (userIdentity: string): ReactNode => {
```

2022-10-31 02:16 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +            ></input>
```suggestion
            <input
                readOnly
                type='checkbox'
                checked={this.state.selectedTaskOwners.has(userIdentity)}
            />
```

2022-10-31 02:16 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +
```suggestion
```

2022-10-31 02:16 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
>      private onTaskOwnersChange = (value: string) => {
```suggestion
    private onTaskOwnersChange = (userIdentity: string) => {
```

2022-11-27 22:31 UTC, naturetime10 commented
Maybe call it `Select Many`. Let's add a background color to the status bar.

2022-11-29 01:42 UTC, duanxianbo commented
@magicoder10

2022-11-30 01:53 UTC, naturetime10 requested changes

2022-11-30 01:53 UTC, naturetime10 commented on tsconfig.json
>  {
Revert

2022-11-30 01:53 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +
```suggestion
```

2022-11-30 01:53 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +
```suggestion
```

2022-11-30 02:10 UTC, naturetime10 requested changes

2022-11-30 02:10 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +export interface KeyboardEventEle {
```suggestion
export interface KeyboardEvent {
```

2022-11-30 02:10 UTC, naturetime10 commented on src/components/pages/Sprints.component.module.scss
> +                    .MultiSelectionTogglerContainer {
```suggestion
                    .MultiSelectionToggleContainer {
```

2022-11-30 02:10 UTC, naturetime10 commented on src/components/pages/Sprints.component.module.scss
> +                        .Toggler {
```suggestion
                        .Toggle {
```

2022-11-30 02:10 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                    ['keydown', 'keyup'].includes(event)
Let's use 2 nested `if` statements instead. Check `Control` and `Meta` key in one `if`. Check `keydown` and `keyup` in another `if`.

2022-11-30 02:10 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +            isInTempMultiSelection: false,
```suggestion
```

2022-11-30 02:10 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                                        className={styles.Toggler}
```suggestion
                                        className={styles.Toggle}
```

2022-11-30 02:10 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                                        `${styles.MultiSelectionTogglerContainer} ${styles.Text}`
```suggestion
                                        `${styles.ActionBar}`
```

2022-11-30 02:10 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                                    <input
Add another div to group checkbox and it's label.

2022-11-30 02:10 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +        }
Can we keep 2 flags: `IsModePerminant` and `allowMultipleSelections`

2022-11-30 02:10 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +}
Maybe be put this is `runtime` package under `libs` to check platform.

2022-11-30 02:10 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +import { chan, multi } from "@lib/csp/csp";
Comments in this files need to addressed.

2022-11-30 02:10 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +    private keyupListener = (event: KeyboardEvent) => {
```suggestion
    private onKeyUp = (event: KeyboardEvent) => {
```

2022-11-30 02:10 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +    private keydownListener = (event: KeyboardEvent) => {
```suggestion
    private onKeyDown = (event: KeyboardEvent) => {
```

2022-11-30 02:10 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +        document.addEventListener('keydown', this.keydownListener, {once: true});
Does it fire multiple times without the last parameter?

2022-11-30 02:10 UTC, naturetime10 commented
Can we use smaller font for checkbox label? Thanks

2022-11-30 02:40 UTC, duanxianbo commented on src/components/pages/Sprints.component.tsx
> +            isInTempMultiSelection: false,
?

2022-11-30 02:42 UTC, duanxianbo commented on src/components/pages/Sprints.component.tsx
> +        }
you mean, rename `isInPermanentMultiSelection` and `isInTempMultiSelection`?

2022-11-30 02:44 UTC, duanxianbo commented on src/libs/event/keyBoardEventMoniter.ts
> +        document.addEventListener('keydown', this.keydownListener, {once: true});
it fires multiple times if you hold the key

2022-11-30 03:07 UTC, duanxianbo commented on src/libs/event/keyBoardEventMoniter.ts
> +import { chan, multi } from "@lib/csp/csp";
can that be done in a separate pr?

2022-11-30 03:29 UTC, duanxianbo commented on src/libs/event/keyBoardEventMoniter.ts
> +import { chan, multi } from "@lib/csp/csp";
oh, sorry, I thought you are referring the csp file

2022-12-01 01:48 UTC, naturetime10 requested changes

2022-12-01 01:48 UTC, naturetime10 commented on src/components/pages/Sprints.component.module.scss
> +                    .ActionBar {
```suggestion
                    }
                    
                    .ActionBar {
```

2022-12-01 01:48 UTC, naturetime10 commented on src/components/pages/Sprints.component.module.scss
> +                    .MultiSelectionToggleContainer {
```suggestion
                    }
                    
                    .MultiSelectionToggleContainer {
```

2022-12-01 01:48 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +import { isMacOs } from '@lib/runtime/utils';
```suggestion
import { isMacOs } from '@lib/runtime/os';
```

2022-12-02 01:24 UTC, naturetime10 requested changes

2022-12-02 01:24 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +    }
```suggestion
    }
    
    private addKeyDownListener() {
        document.addEventListener('keydown', this.onKeyDown, {once: true});
    }
```

2022-12-02 01:24 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                            this.state.allowMultiSelection
```suggestion
```

2022-12-02 01:24 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                            allowMultiSelection: event === 'keydown',
```suggestion
                            allowMultiSelection: event === 'keydown',
```

2022-12-02 01:24 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                        this.isSelectionModePermanent = event === 'keyup';
```suggestion
```

2022-12-02 01:24 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                                        onClick={this.toggleMultiSelection}
```suggestion
                                        onClick={this.toggleMultiSelectionPermanently}
```

2022-12-02 01:24 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                                            Select{' '}
```suggestion
                                            Select 
```

2022-12-02 01:24 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                                                ? 'Many'
```suggestion
                                                ? 'many'
```

2022-12-02 01:24 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                                                : 'Single'}
```suggestion
                                                : 'single'}
```

2022-12-02 01:24 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +        }
```suggestion
       if (this.state.allowMultiSelection) {
           this.isSelectionModePermanent = false;
       }
       
```

2022-12-02 02:44 UTC, naturetime10 requested changes

2022-12-02 02:44 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                const keyboardEventEle = await this.keyBoardEventChan!.pop();
```suggestion
                const internalKeyboardEvent = await this.keyBoardEventChan!.pop();
```

2022-12-02 02:44 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                if (keyboardEventEle === undefined) {
```suggestion
                if (internalKeyboardEvent === undefined) {
```

2022-12-02 02:44 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                const event = keyboardEventEle.event;
```suggestion
                const event = internalKeyboardEvent.event;
```

2022-12-02 03:13 UTC, duanxianbo commented on src/components/pages/Sprints.component.tsx
> +                            this.state.allowMultiSelection
removed

2022-12-02 03:14 UTC, duanxianbo commented on src/libs/event/keyBoardEventMoniter.ts
> +    }
removed

2022-12-02 03:14 UTC, duanxianbo commented on src/components/pages/Sprints.component.tsx
> +                        this.isSelectionModePermanent = event === 'keyup';
removed

2022-12-02 03:15 UTC, duanxianbo commented on src/components/pages/Sprints.component.tsx
> +                                            Select{' '}
can not, the linter will force a space with {' '}

2022-12-02 03:22 UTC, duanxianbo commented
with the latest logic, when user hold ctrl, he can still click the switch button

2022-12-02 10:01 UTC, naturetime10 requested changes

2022-12-02 10:01 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                    (getPlatform() === 'Mac' && keyboardEvent.metaKey)
```suggestion
                    (getPlatform() === 'Mac' && keyboardEvent.key === 'Meta')
```

2022-12-02 10:01 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                                        onClick={this.toggleMultiSelectionPermanently}
```suggestion
                                        onClick={this.onMultiSelectionToggleClick}
```

2022-12-02 10:01 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +    private toggleMultiSelectionPermanently = () => {
```suggestion
    private onMultiSelectionToggleClick = () => {
```

2022-12-02 10:01 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +        this.isSelectionModePermanent = !this.state.allowMultiSelection
```suggestion
        this.isSelectionModePermanent = !this.state.allowMultiSelection;
```

2022-12-02 10:01 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +
```suggestion
```

2022-12-02 10:01 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
>              }
```
if (hasValue) {
    this.state.selectedTaskOwners.delete(value);
} else if (this.state.allowMultiSelection && value !== userAll) {
    this.state.selectedTaskOwners.delete(userAll);
    this.state.selectedTaskOwners.add(value);
} else {
    this.state.selectedTaskOwners.clear();
    this.state.selectedTaskOwners.add(value);
}
```

2022-12-02 10:01 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +    metaKey?: boolean
```suggestion
```

2022-12-02 10:01 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +    key: string
```suggestion
    key: KeyboardKey
```

2022-12-02 10:01 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +    event: KeyboardEventType,
```suggestion
    eventType: KeyboardEventType,
```

2022-12-02 10:01 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +    private holdKeySet = new Set<string>()
```suggestion
    private keyEventChan = chan<InternalKeyboardEvent>();
    private keyEventMultiChan = multi<InternalKeyboardEvent>(this.keyEventChan);
    private holdKeySet = new Set<KeyboardKey>();
```

2022-12-02 10:01 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +            event: "keyup",
```suggestion
            eventType: 'keyup',
```

2022-12-02 10:01 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +            key: event.key,
Can we create a helper to map system key to a customly define union type `KeyboardKey`

2022-12-02 10:01 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +            metaKey: event.metaKey
```suggestion
```
Pass this info as `'Meta'` through above `key` property instead.

2022-12-02 10:01 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +        document.addEventListener('keydown', this.onKeyDown, {once: true});
```suggestion
```

2022-12-02 10:01 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +        })
```suggestion
        });
```

2022-12-02 10:01 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +        })
Do the same as keyUp event listener.

2022-12-02 10:01 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +        this.holdKeySet.add(event.key)
```suggestion
        this.holdKeySet.add(event.key);
```

2022-12-03 02:55 UTC, duanxianbo commented on src/libs/event/keyBoardEventMoniter.ts
> +        document.addEventListener('keydown', this.onKeyDown, {once: true});
do not think we can remove this, since the option = {once: true} means it only fires once and we need to re add the listener somewhere

2022-12-03 03:00 UTC, naturetime10 requested changes

2022-12-03 03:00 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +        document.addEventListener('keydown', this.onKeyDown, {once: true});
@duanxianbo Then use `holdKeySet` to dedup instead?

2022-12-03 09:26 UTC, naturetime10 requested changes

2022-12-03 09:26 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +        this.holdKeySet.add(keyboardKey);
```suggestion
        this.holdKeySet.add(keyboardKey);
        this.keyEventChan.put({
            key: keyboardKey,
            eventType: 'keydown',
        });
```

2022-12-03 09:26 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +type KeyboardKey = typeof KeyboardKeys[number];
```suggestion
type KeyboardKey = 'Control' | 'Meta';
```

2022-12-03 09:26 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +    }
Can we define `keyMap` record mapping JavaScript event key to `KeyboardKey` instead?

2022-12-03 09:26 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +            this.holdKeySet.delete(keyboardKey);
```suggestion
            this.holdKeySet.delete(keyboardKey);
            this.keyEventChan.put({
                key: keyboardKey,
                eventType: 'keyup',
            });
```

2022-12-03 13:22 UTC, duanxianbo commented on src/libs/event/keyBoardEventMoniter.ts
> +    }
Actually in most cases, the system key to the keyboard key will be the same, like 'Control' map to 'Control', is it better to do a set instead?

2022-12-03 15:51 UTC, duanxianbo commented on src/libs/event/keyBoardEventMoniter.ts
> +type KeyboardKey = typeof KeyboardKeys[number];
done

2022-12-03 15:52 UTC, duanxianbo commented on src/libs/event/keyBoardEventMoniter.ts
> +    }
done with a map

2022-12-03 22:11 UTC, naturetime10 requested changes

2022-12-03 22:11 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +
```suggestion
```

2022-12-03 22:11 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +const keyMap: Record<InternalEventKey, KeyboardKey> = {
```suggestion
const keyMap: Record<string, KeyboardKey> = {
```

2022-12-03 22:11 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +type InternalEventKey = 'Control';
```suggestion
```

2022-12-03 22:11 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +        const keyboardKey = keyMap[event.key as InternalEventKey]
```suggestion
       return keyMap[event.key]
```

2022-12-03 22:11 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +    private getKeyBoardKey(event: KeyboardEvent): null | KeyboardKey {
```suggestion
    private getKeyBoardKey(event: KeyboardEvent): undefined | KeyboardKey {
```

2022-12-03 22:11 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +        return null;
```suggestion
```

2022-12-03 22:11 UTC, naturetime10 commented on src/libs/event/keyBoardEventMoniter.ts
> +        if (keyboardKey === null || this.isKeyHold(keyboardKey)) {
```suggestion
        if (keyboardKey === undefined || this.isKeyHold(keyboardKey)) {
```

2022-12-04 02:06 UTC, naturetime10 approved these changes

2022-12-04 02:08 UTC, merged