Sort participants by fullname
teamyapp/teamy-web pull request #413
Opened 2022-12-09 02:11 UTC by duanxianbo

2022-12-09 07:43 UTC, naturetime10 requested changes

2022-12-09 07:43 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +        } else if (participantA.user.fullName.toUpperCase() > participantB.user.fullName.toUpperCase()){
participantA.user.fullName.toUpperCase()
Can we save the value in a variable and reuse it in this function?

2022-12-09 07:43 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +            return 1
Should 1 and -1 be reversed?

2022-12-12 03:44 UTC, duanxianbo commented on src/components/pages/Sprints.component.tsx
> +            return 1
I think it is right 
![image](https://user-images.githubusercontent.com/6356492/206956022-76299dd4-c8c1-4b1b-b425-3ddf0e8a1ac4.png)

2022-12-14 01:38 UTC, naturetime10 approved these changes

2022-12-15 02:49 UTC, merged