Add confirm and cancel buttons to task creation
teamyapp/teamy-web pull request #425
Opened 2023-01-07 19:58 UTC by duanxianbo

![image](https://user-images.githubusercontent.com/6356492/211215365-85ef75e3-9f4e-45b0-844b-f6140bbebd2f.png)

2023-01-08 19:37 UTC, duanxianbo commented
@magicoder10

2023-01-08 23:27 UTC, naturetime10 commented
Can we make check mark smaller in the confirm button?

2023-01-14 20:03 UTC, naturetime10 requested changes

2023-01-14 20:03 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +                                <div className={styles.SaveTaskEditionIcon}>
```suggestion
                                <div className={styles.SaveTaskIcon}>
```

2023-01-14 20:03 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +                                onClick={this.onSaveTaskEditionClick}
```suggestion
                                onClick={this.onSaveTaskClick}
```

2023-01-14 20:03 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +                                onClick={this.onCancelTaskEditionClick}
```suggestion
                                onClick={this.onCancelTaskClick}
```

2023-01-14 20:03 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +                                <div className={styles.CancelTaskEditionIcon}>
```suggestion
                                <div className={styles.CancelTaskIcon}>
```

2023-01-14 20:03 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +    assignOwnerActive: boolean;
```suggestion
    assigningOwner: boolean;
```

2023-01-14 20:03 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +    defaultToCurrentUser?: boolean;
```suggestion
```

2023-01-14 20:03 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +    defaultToCurrentUser?: boolean;
If we are already able to pass in taskOwnerId through props, why are we having this field?

2023-01-14 20:03 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +        } else {
```suggestion
```

2023-01-14 20:03 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +    defaultToCurrentUser?: boolean;
Let the parent of this component decide who should be the default user.

2023-01-14 20:03 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.module.scss
> +    .SaveTaskEditionIcon {
```suggestion
    .SaveTaskIcon {
```

2023-01-14 20:03 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.module.scss
> +    .CancelTaskEditionIcon {
```suggestion
    .CancelTaskIcon {
```

2023-01-14 20:41 UTC, naturetime10 requested changes

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/InlineTask.tsx
> +    onShowPotantialTaskOwnersToUpdateTask?: (
```suggestion
    onShowPotantialTaskOwners?: (
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +    onShowPotantialTaskOwnersToCreateTask?: (
```suggestion
    onShowPotantialTaskOwners?: (
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/InlineTask.tsx
> +        this.props.onShowPotantialTaskOwnersToUpdateTask?.call(
```suggestion
        this.props.onShowPotantialTaskOwners?.call(
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/Backlog.component.tsx
> +    ) => void;
Can we move `onShowPotantialTaskOwnersToCreateTask` above `onShowPotantialTaskOwnersToUpdateTask`?

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/Backlog.component.tsx
> +                                    onShowPotantialTaskOwnersToCreateTask={
```suggestion
                                    onShowPotantialTaskOwners={
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/Backlog.component.tsx
> +
```suggestion
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/Backlog.component.tsx
> +                    onShowPotantialTaskOwnersToUpdateTask={
```suggestion
                    onShowPotantialTaskOwners={
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/App.component.tsx
> +
```suggestion
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/App.component.tsx
> +                    onShowPotantialTaskOwnersToUpdateTask={this.onShowPotantialTaskOwnersToUpdateTask}
```suggestion
                    onShowPotantialTaskOwners={this.onShowPotantialTaskOwnersToUpdateTask}
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/App.component.tsx
> +                                                onShowPotantialTaskOwnersToCreateTask={
Put `CreateTask` handler before `UpdateTask` handler.

2023-01-14 20:41 UTC, naturetime10 commented on src/components/App.component.tsx
> +                                                onShowPotantialTaskOwnersToCreateTask={
Put `CreateTask` handler before `UpdateTask` handler.

2023-01-14 20:41 UTC, naturetime10 commented on src/components/App.component.tsx
> +    private onSelectOwner?: (taskOwnerId?: number) => void;
Does it work if it's not part of state?

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/Kanban.tsx
> +    onShowPotantialTaskOwnersToCreateTask?: (
Put `CreateTask` handler before `UpdateTask` handler.

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/Kanban.tsx
> +                        onShowPotantialTaskOwnersToCreateTask={
Put `CreateTask` handler before `UpdateTask` handler.

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/Kanban.tsx
> +                        onShowPotantialTaskOwnersToUpdateTask={
```suggestion
                        onShowPotentialTaskOwners={
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/Kanban.tsx
> +                        onShowPotantialTaskOwnersToUpdateTask={
```suggestion
                        onShowPotentialTaskOwners={
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/Kanban.tsx
> +                        onShowPotantialTaskOwnersToUpdateTask={
```suggestion
                        onShowPotentialTaskOwners={
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/SelectTaskOwnersPopupComponent.tsx
> +
```suggestion
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/TaskListSections/AwaitingSection.tsx
> +    onShowPotantialTaskOwnersToUpdateTask?: (
```suggestion
    onShowPotentialTaskOwners?: (
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/TaskListSections/AwaitingSection.tsx
> +                        onShowPotantialTaskOwnersToUpdateTask={
```suggestion
                        onShowPotentialTaskOwners={
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/TaskListSections/DeliveredSection.tsx
> +                        onShowPotantialTaskOwnersToUpdateTask={
```suggestion
                        onShowPotentialTaskOwners={
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/TaskListSections/DeliveredSection.tsx
> +                            this.props.onShowPotantialTaskOwnersToUpdateTask
```suggestion
                            this.props.onShowPotentialTaskOwners
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/TaskListSections/AwaitingSection.tsx
> +                            this.props.onShowPotantialTaskOwnersToUpdateTask
```suggestion
                            this.props.onShowPotentialTaskOwners
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/TaskListSections/InProgressSection.tsx
> +    onShowPotantialTaskOwnersToUpdateTask?: (
```suggestion
    onShowPotentialTaskOwners?: (
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/TaskListSections/InProgressSection.tsx
> +                        onShowPotantialTaskOwnersToUpdateTask={
```suggestion
                        onShowPotentialTaskOwners={
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/TaskListSections/InProgressSection.tsx
> +                            this.props.onShowPotantialTaskOwnersToUpdateTask
```suggestion
                            this.props.onShowPotentialTaskOwners
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/TaskListSections/NeedAttentionSection.tsx
> +    onShowPotantialTaskOwnersToUpdateTask?: (
```suggestion
    onShowPotentialTaskOwners?: (
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/TaskListSections/NeedAttentionSection.tsx
> +                        onShowPotantialTaskOwnersToUpdateTask={
```suggestion
                        onShowPotentialTaskOwners={
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/TaskListSections/NeedAttentionSection.tsx
> +                            this.props.onShowPotantialTaskOwnersToUpdateTask
```suggestion
                            this.props.onShowPotentialTaskOwners
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/TaskListSections/TaskListItem.tsx
> +    onShowPotantialTaskOwnersToUpdateTask?: (
```suggestion
    onShowPotentialTaskOwners?: (
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/TaskListSections/TaskListItem.tsx
> +                    onShowPotantialTaskOwnersToUpdateTask={
```suggestion
                    onShowPotentialTaskOwners={
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/TaskListSections/TaskListItem.tsx
> +                        this.props.onShowPotantialTaskOwnersToUpdateTask
```suggestion
                        this.props.onShowPotentialTaskOwners
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/TaskListSections/UpcomingSection.tsx
> +    onShowPotantialTaskOwnersToCreateTask?: (
Let's put `create task` handler before `update task` handler

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/TaskListSections/UpcomingSection.tsx
> +                                    onShowPotantialTaskOwnersToCreateTask={
```suggestion
                                    onShowPotentialTaskOwners={
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/TaskListSections/UpcomingSection.tsx
> +                        onShowPotantialTaskOwnersToUpdateTask={
```suggestion
                        onShowPotentialTaskOwners={
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/internal/inlineTask.shared.scss
> +            width: $actionIconSize;
```suggestion
            --icon-box-size: #{$actionIconSize};
            --icon-size: #{$actionIconSize};
            align-items: center;
            border-radius: 4px;
            display: flex;
            height: $actionIconSize;
            justify-content: center;
            padding: 4px;
            user-select: none;
            width: $actionIconSize;
```

2023-01-14 20:41 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +    onShowPotantialTaskOwnersToCreateTask?: (
Let's put `createTask` handler before `updateTask` handler.

2023-01-14 20:41 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                        onShowPotantialTaskOwnersToCreateTask={
Let's put `createTask` handler before `updateTask` handler.

2023-01-14 20:41 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                                onShowPotantialTaskOwnersToUpdateTask={
Let's put `createTask` handler before `updateTask` handler.

2023-01-14 22:00 UTC, duanxianbo commented on src/components/App.component.tsx
> +    private onSelectOwner?: (taskOwnerId?: number) => void;
it does work, however it should better not, I think it is because we are not really do pure component(that update only because state and props change), do you want to put them into state?

2023-01-19 04:07 UTC, naturetime10 requested changes
Please format code. Thanks

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.module.scss
> +    .CancelTaskIcon {
```suggestion
    .CancelEditTaskIcon {
```

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +            <>
```suggestion
            <Fragment>
```

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +            </>
```suggestion
            </Fragment>
```

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +                                    onClick={this.onCancelTaskClick}
```suggestion
                                    onClick={this.onCancelEditTaskClick}
```

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +                                    <div className={styles.CancelTaskIcon}>
```suggestion
                                    <div className={styles.CancelEditTaskIcon}>
```

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +                    onSelectOwner={this.handleTaskOwnerSelected}
```suggestion
                    onSelectOwner={this.onSelectTaskOwner}
```

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +                    onClose={this.handleTaskOwnersPopupClose}
```suggestion
                    onClose={this.onTaskOwnersPopupClose}
```

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +    private handleTaskOwnersPopupClose = () => {
```suggestion
    private onTaskOwnersPopupClose = () => {
```

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +    private handleTaskOwnerSelected = (ownerUserId?: number) => {
```suggestion
    private onSelectTaskOwner = (ownerUserId?: number) => {
```

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +    private onCancelTaskClick = () => {
```suggestion
    private onCancelEditTaskClick = () => {
```

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/InlineTask.tsx
> +        createRef<SelectTaskOwnersPopupComponent>();
```suggestion
        createRef<SelectTaskOwnersPopupComponent>();
        
```

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/InlineTask.tsx
> +        }
I think we can get ref of the button inside `renderAssignOwner` and only define a `getBoundingClientRect` instead. The extra closure for `this.getBoundingClientRect = () => {}` is not needed.

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/InlineCreateTask.tsx
> +        }
I think we can get ref of the button inside `renderAssignOwner` and only define a `getBoundingClientRect` instead. The extra closure for `this.getBoundingClientRect = () => {}` is not needed.

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/Modals/TaskDetailModal.component.tsx
> +                                <div className={styles.SaveAction}>
Can we add a screenshot for those buttons in the PR?

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/Modals/TaskDetailModal.component.tsx
> +    private handleTaskOwnerSelected = (ownerUserId?: number) => {
```suggestion
    private onTaskOwnerSelected = (ownerUserId?: number) => {
```

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/Modals/TaskDetailModal.component.tsx
> +    private handleTaskOwnersPopupClose = () => {
```suggestion
    private onTaskOwnersPopupClose = () => {
```

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/TaskListSections/UpcomingSection.tsx
> +    private readonly graphSource: GraphSource;
```suggestion
    private readonly localStore: LocalStore;
    
```

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/TaskListSections/UpcomingSection.tsx
> +        this.graphSource = props.deps.graphSource;
```suggestion
        this.localStore = props.deps.localStore;
```

2023-01-19 04:07 UTC, naturetime10 commented on src/components/internal/TaskListSections/UpcomingSection.tsx
> +                                        this.graphSource.currentUser()?.id
```suggestion
                                        this.localStore.currUserId
```

2023-01-22 22:30 UTC, duanxianbo commented on src/components/internal/Modals/TaskDetailModal.component.tsx
> +                                <div className={styles.SaveAction}>
it is in the pr description

2023-01-22 22:46 UTC, duanxianbo commented on src/components/internal/InlineTask.tsx
> +        }
the button is the element right? agree that we donot need the extra closure, but we need to bind the element to the function
`
        const element = event.currentTarget as HTMLDivElement;
        this.getBoundingClientRect = element.getBoundingClientRect.bind(element);
`

2023-01-23 00:54 UTC, naturetime10 approved these changes

2023-01-23 01:09 UTC, merged