Stop retry for unauthorized errors
teamyapp/teamy-web pull request #427
Opened 2023-01-08 20:58 UTC by duanxianbo

2023-01-11 06:30 UTC, naturetime10 requested changes

2023-01-11 06:30 UTC, naturetime10 commented on src/libs/retry/infinite.test.ts
> +
```suggestion
```

2023-01-11 06:30 UTC, naturetime10 commented on src/libs/retry/infinite.ts
> +                retries++;
```suggestion

                retries++;
```

2023-01-11 06:30 UTC, naturetime10 commented on src/libs/retry/infinite.ts
> +                    await this.beforeThreadSleep?.call(null)
Can we add `beforeSkipRetry`  instead of using `beforeThreadSleep`?

2023-01-11 06:30 UTC, naturetime10 commented on src/libs/retry/infinite.ts
> +                await this.runtime.threadSleep(duration);
Undo this change.

2023-01-11 06:30 UTC, naturetime10 commented on src/libs/retry/infinite.ts
> +        private beforeThreadSleep?: (duration?: Duration) => Promise<void>,
```suggestion
        private beforeSkipRetry?: () => Promise<void>,
```

2023-01-12 01:15 UTC, duanxianbo commented on src/libs/retry/infinite.ts
> +                    await this.beforeThreadSleep?.call(null)
yes, so you are saying pass another optional param beforeSkipRetry

2023-01-12 01:59 UTC, naturetime10 requested changes

2023-01-12 01:59 UTC, naturetime10 commented on src/libs/retry/infinite.test.ts
> +        beforeSkipRetry = async () => {beforeSleepSemaphore.release()}
```suggestion
        beforeSkipRetry = async () => {
            beforeSleepSemaphore.release();
        }
```

2023-01-12 01:59 UTC, naturetime10 commented on src/libs/retry/infinite.test.ts
>      let beforeSleepSemaphore: Semaphore;
```suggestion
    let beforeRetrySemaphore: Semaphore;
```

2023-01-12 01:59 UTC, naturetime10 commented on src/libs/retry/maxCount.test.ts
> +            deepStrictEqual(errorRes, error);
How about only compare `errorCode`. Error message is only for human to read and is subject to change in the future?

2023-01-12 01:59 UTC, naturetime10 commented on src/libs/retry/maxCount.ts
> +                retries++
```suggestion

                retries++
```

2023-01-12 01:59 UTC, naturetime10 commented on src/libs/retry/retry.ts
> +}
Are we using it in production or testing code only? If only for testing code, can we keep it in test modules?

2023-01-12 01:59 UTC, naturetime10 commented on src/libs/retry/maxCount.ts
> +                retries++
yarn format

2023-01-12 02:49 UTC, duanxianbo commented on src/libs/retry/maxCount.test.ts
> +            deepStrictEqual(errorRes, error);
yes

2023-01-12 09:00 UTC, naturetime10 approved these changes

2023-01-12 09:00 UTC, naturetime10 commented on src/libs/retry/infinite.test.ts
> +}
test-utils.ts

2023-01-12 09:00 UTC, naturetime10 commented on src/libs/retry/infinite.test.ts
> +}
Please make this change and merge afterwards.

2023-01-13 02:01 UTC, merged