Stop retry when err is a clientInteraction
teamyapp/teamy-web pull request #451
Opened 2023-03-26 22:08 UTC by duanxianbo

(task:13603)

2023-03-27 02:16 UTC, naturetime10 requested changes

2023-03-27 02:16 UTC, naturetime10 commented on src/libs/retry/infinite.test.ts
> +describe.only('InfiniteRetry', () => {
```suggestion
describe('InfiniteRetry', () => {
```

2023-03-29 09:41 UTC, naturetime10 requested changes

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/retry/infinite.ts
> +        context?: Record<string, string>,
```suggestion
        context: Record<string, string>,
        execute: () => Promise<InternalError | undefined>,
```

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/retry/infinite.ts
> +
```suggestion
```

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/retry/testing.ts
> +
```suggestion
```

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/retry/retry.ts
> +        context?: Record<string, string>,
```suggestion
        context: Record<string, string>,
        execute: () => Promise<InternalError | undefined>,
```

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/retry/maxCount.ts
> +
```suggestion
```

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/retry/maxCount.ts
> +
```suggestion
```

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/retry/maxCount.ts
> +
```suggestion
```

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/retry/maxCount.ts
> +        context?: Record<string, string>,
```suggestion
        context: Record<string, string>,
        execute: () => Promise<InternalError | undefined>,
```

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/retry/timeout.ts
> +        context?: Record<string, string>,
```suggestion
        context: Record<string, string>,
        execute: () => Promise<InternalError | undefined>,
```

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/retry/timeout.ts
> +
```suggestion
```

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/retry/timeout.ts
> +                }, context);
```suggestion
                const errorCategory = getErrCategory(err);
                this.logger.logWithContext('Warning', {
                    [ErrCategoryProp]: errorCategory,
                }, context);
                await this.beforeRetryDelay?.call(null);
```

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/telemetry/Props.ts
> +export const ErrCodeProp = 'ErrCode';
```suggestion
export const ErrCodeProp = 'ErrorCode';
```

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/telemetry/Props.ts
> +export const ErrCategoryProp = 'ErrCategory';
```suggestion
export const ErrCategoryProp = 'ErrorCategory';
```

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/telemetry/TelemetryClient.ts
> +
```suggestion
```

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/telemetry/TelemetryClient.ts
> +export class TelemetryClient implements TelemetryClientInterface {
```suggestion
export class TelemetryClient {
```

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/telemetry/TelemetryClient.ts
> +
```suggestion
```

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/telemetry/TelemetryClient.ts
> +}
```suggestion
```

I think we can create and pass in `fakeHttpClient` instead.

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/telemetry/RawLogger.ts
> +import { TelemetryClient, TelemetryClientInterface } from './TelemetryClient';
```suggestion
import { TelemetryClient } from './TelemetryClient';
```

2023-03-29 09:41 UTC, naturetime10 commented on src/libs/telemetry/RawLogger.ts
> +        telemetryClient: TelemetryClientInterface,
```suggestion
        telemetryClient: TelemetryClient,
```

2023-03-29 09:46 UTC, naturetime10 commented
More comments will be provided for test code.

2023-03-30 01:29 UTC, naturetime10 requested changes

2023-03-30 01:29 UTC, naturetime10 commented on src/libs/retry/infinite.test.ts
> +            beforeSleepSemaphore.release();
Is calling `beforeSleepSemaphore` expected?

2023-03-30 01:29 UTC, naturetime10 commented on src/libs/retry/infinite.test.ts
> +                sleepAwakeCount: 2,
```suggestion
                sleepAwakeCount: 2,
                expectRetries: 3,
                expectErr: {
                    errorCode: CLIENT_INTERACTION_ERR,
                },
```

2023-03-30 01:29 UTC, naturetime10 commented on src/libs/retry/infinite.test.ts
> +                sleepAwakeCount: 4,
```suggestion
                sleepAwakeCount: 4,
                expectRetries: 5,
                expectErr: undefined,
```

2023-03-30 01:29 UTC, naturetime10 commented on src/libs/retry/infinite.test.ts
> +                strictEqual(errorRes?.errorCode, expectErr?.errorCode);
```suggestion
                strictEqual(expectRetries, retriesRes);
                strictEqual(expectErr?.errorCode, errorRes?.errorCode);
```

2023-03-30 01:29 UTC, naturetime10 commented on src/libs/retry/maxCount.test.ts
> +
```suggestion
```

2023-03-30 01:29 UTC, naturetime10 commented on src/libs/retry/timeout.test.ts
> +                    ),
Can we put this into a new variable called `newDate`

2023-03-30 01:50 UTC, duanxianbo commented on src/libs/retry/infinite.test.ts
> +            beforeSleepSemaphore.release();
it is used for testing purpose, we have a loop to check the runtime sleep and awake behaviours, this is used to trigger before sleep and after sleep signals, for client interaction err, we donot call runtime.sleep(no need to sleep) to release this semaphore, instead we use this beforeSkipRetry to release it

2023-03-30 02:49 UTC, naturetime10 requested changes

2023-03-30 02:49 UTC, naturetime10 commented on src/libs/network/middleware/clientHTTPWithRetry.ts
> +                    context!,
```suggestion
                    context || {},
```

2023-03-30 02:52 UTC, naturetime10 approved these changes

2023-03-30 02:52 UTC, merged