Get and set active sprint
teamyapp/teamy-web pull request #460
Opened 2023-04-16 20:45 UTC by duanxianbo

(task:15606)

<img width="1515" alt="image" src="https://user-images.githubusercontent.com/6356492/233791196-87582b8d-18ea-4a9b-9973-2c482de2a0b0.png">

2023-04-17 01:38 UTC, duanxianbo commented
@magicoder10 we can review this one too

2023-04-18 08:32 UTC, naturetime10 commented
May be use this icon: star_rate

2023-04-18 08:33 UTC, naturetime10 commented
Let's add more top and bottom paddings.

2023-04-18 08:42 UTC, naturetime10 requested changes

2023-04-18 08:42 UTC, naturetime10 commented on src/client/sprint.client.ts
> +                                    }
```suggestion
```

2023-04-18 08:42 UTC, naturetime10 commented on src/client/sprint.client.ts
> +                                        }
```suggestion
```

2023-04-18 08:42 UTC, naturetime10 commented on src/client/sprint.client.ts
> +                                }
```suggestion
```

2023-04-18 08:42 UTC, naturetime10 commented on src/client/task.client.ts
> +                                }
```suggestion
```

2023-04-18 08:42 UTC, naturetime10 commented on src/client/task.client.ts
> +                                }
```suggestion
```

2023-04-18 08:42 UTC, naturetime10 commented on src/client/task.client.ts
> +                                }
```suggestion
```

2023-04-18 08:42 UTC, naturetime10 commented on src/client/team.client.ts
> +                                    }
```suggestion
```

2023-04-18 08:42 UTC, naturetime10 commented on src/client/team.client.ts
> +                                    }
```suggestion
```

2023-04-18 08:42 UTC, naturetime10 commented on src/client/team.client.ts
> +                                        }
```suggestion
```

2023-04-18 08:42 UTC, naturetime10 commented on src/client/team.client.ts
> +
```suggestion
```

2023-04-18 08:42 UTC, naturetime10 commented on src/components/App.component.module.scss
> +
```suggestion
```

2023-04-18 08:42 UTC, naturetime10 commented on src/components/App.component.module.scss
> +            .BannerAction {
```suggestion
            }
            
            .BannerLink {
```

2023-04-18 08:42 UTC, naturetime10 commented on src/components/App.component.tsx
> +                activeSprint.id !== currentSprintId
Let's make this a separate variable.

2023-04-18 08:42 UTC, naturetime10 commented on src/libs/ui/Banner.module.scss
> +
```suggestion
```

2023-04-18 08:42 UTC, naturetime10 commented on src/libs/ui/Banner.tsx
> +    private handleClose = () => {
```suggestion
    private onCloseClick = () => {
```

2023-04-18 08:42 UTC, naturetime10 commented on src/storage/graph/team.node.ts
> +
```suggestion
```

2023-04-18 08:42 UTC, naturetime10 commented on src/storage/syncer/mutation.ts
> +    | 'TeamActiveSprint';
If backend is changed to use `UpdateTeam`, then this is not needed anymore

2023-04-22 02:50 UTC, duanxianbo commented
@magicoder10

2023-04-22 19:28 UTC, naturetime10 requested changes

2023-04-22 19:28 UTC, naturetime10 commented on src/components/App.component.tsx
> +                                                            .onActiveSprintSelect
OnGotoActiveSprintClick

2023-04-22 19:28 UTC, naturetime10 commented on src/components/App.component.tsx
> +import { ButtonUI } from '@lib/ui/Button';
Are we still using this?

2023-04-22 19:28 UTC, naturetime10 commented on src/components/App.component.tsx
> +        )
Can we simplify/breakdown this logic to remove double negative.

2023-04-22 19:28 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +                                <MaterialIconUI>{!this.isActiveSprint() ? 'directions_run' : 'star_rate'}</MaterialIconUI>
Can we reverse the condition and remove the negation?

2023-04-22 19:28 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +                                <MaterialIconUI>{!this.isActiveSprint() ? 'directions_run' : 'star_rate'}</MaterialIconUI>
Can we add a screenshot for this?

2023-04-22 19:28 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +                                <MaterialIconUI>{!this.isActiveSprint() ? 'directions_run' : 'star_rate'}</MaterialIconUI>
Can we show the icon on the right of sprint name?

2023-04-22 19:28 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +                    message={'Set current sprint to active sprint'}
Set as active sprint

2023-04-22 19:28 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +                            onClick={this.onSetCurrentSprintClick}
OnSetActiveSprintClick

2023-04-22 19:28 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +        return currentTeam?.activeSprint && currentTeam.activeSprint.id === this.state.currentSprint?.id;
Let's break & to 2 lines

2023-04-22 19:28 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +    private onSetCurrentSprintClick = () => {
onSetAsActiveSprintClick

2023-04-22 19:28 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +        const currentTeam = this.graphSource.currentTeam()
;

2023-04-22 19:28 UTC, naturetime10 commented on src/libs/ui/Banner.tsx
> +
Remove empty line.

2023-04-22 19:28 UTC, naturetime10 commented on src/storage/graph/team.node.ts
> +
Remove empty line.

2023-04-22 19:28 UTC, naturetime10 commented on src/storage/syncer/mutation.ts
> +    | 'SprintParticipant'
;

2023-04-22 19:28 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +    UpdateTeamActiveSprintPayload,
Remove line

2023-04-22 19:28 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +    debugger
Remove debugger

2023-04-26 01:28 UTC, naturetime10 approved these changes

2023-04-26 01:28 UTC, naturetime10 commented on src/components/internal/SprintsHeaderSection.component.tsx
> +
```suggestion
```

2023-04-26 01:28 UTC, naturetime10 commented on src/components/internal/shared.scss
> +            &:not(.Disabled) {
```suggestion

            &:not(.Disabled) {
```

2023-04-26 01:30 UTC, merged