Add installed apps and managed apps tabs
teamyapp/teamy-web pull request #533
Opened 2024-01-13 20:51 UTC by duanxianbo

[(task:18944)](https://staging.teamyapp.com/teams/107/tasks/18944)

<img width="631" alt="image" src="https://github.com/teamyapp/teamy-web/assets/6356492/df3abdca-6295-49d4-8dd8-32ea7bd9538a">
<img width="926" alt="image" src="https://github.com/teamyapp/teamy-web/assets/6356492/db7bc031-d768-4b7e-bc1c-da04a6441b18">

2024-01-14 17:12 UTC, naturetime10 requested changes

2024-01-14 17:12 UTC, naturetime10 commented on src/client/team.client.ts
> +    // TODO: the query will be simplified(app version part) once we have apps query
```suggestion
    // TODO: simplify query(app version part) once we have apps query
```

2024-01-14 17:12 UTC, naturetime10 commented on src/components/pages/Marketplace/InstalledTab.component.tsx
> +
```suggestion
```

2024-01-14 17:12 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/CreateAppSecretModal.component.module.scss
> -    .AppSecret {
Is it find to remove this?

2024-01-14 17:12 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/CreateAppVersionModal.component.tsx
> +                            label={'App Name'}
I though in the past we are creating a new app version and then will ask the developer to upload app package and extract app name and description from manifest. Do we have a new plan now?

2024-01-14 17:12 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/CreateAppVersionModal.component.tsx
> +
```suggestion
```

2024-01-14 17:12 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal.component.tsx
> +
```suggestion
```

2024-01-14 17:12 UTC, naturetime10 commented on src/entity/money.ts
> +    currency: string;
So this can't be a enum?

2024-01-14 17:12 UTC, naturetime10 commented on src/storage/graph/app.node.ts
> +        debugger
```suggestion
```

2024-01-14 17:12 UTC, naturetime10 commented on src/storage/graph/app.node.ts
> +
```suggestion
```

2024-01-14 17:12 UTC, naturetime10 commented on src/storage/graph/app.node.ts
> +    public get latestVersionForTeam(): AppVersionNode | undefined {
Should we change the model and make this a function to allow user passing in team ID to filter out latest version for a specific team?

2024-01-14 17:12 UTC, naturetime10 commented on src/storage/graph/appInstallation.node.ts
> +
```suggestion
```

2024-01-14 17:12 UTC, naturetime10 commented on src/storage/graph/appVersion.node.ts
> +
```suggestion
```

2024-01-14 17:12 UTC, naturetime10 commented on src/storage/graph/team.node.ts
> +        return apps;
Are we able to do a filter and map instead?

2024-01-14 17:12 UTC, naturetime10 commented on src/storage/graph/team.node.ts
> +        }
Are we able to do a filter and map instead?

2024-01-14 17:12 UTC, naturetime10 commented on src/storage/states/app.state.ts
> +import {PluginAppState} from '@core/storage/states/pluginApp.state';
```suggestion
import { PluginAppState } from '@core/storage/states/pluginApp.state';
```

2024-01-14 17:12 UTC, naturetime10 commented on src/storage/states/pluginApp.state.ts
> +            ),
Can we move this between line 14 and line 15?

2024-01-14 17:12 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +
```suggestion
```

2024-01-14 17:12 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +
```suggestion
```

2024-01-14 17:12 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +        if (secretId === undefined) {
```suggestion
        if (!secretId) {
```

2024-01-14 17:12 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +
```suggestion
```

2024-01-14 17:12 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +
```suggestion
```

2024-01-15 01:46 UTC, duanxianbo commented on src/components/pages/Marketplace/Modals/CreateAppSecretModal.component.module.scss
> -    .AppSecret {
I did not find anywhere we use this class

2024-01-15 01:46 UTC, duanxianbo commented on src/storage/graph/app.node.ts
> +    public get latestVersionForTeam(): AppVersionNode | undefined {
as we fetch managed apps and app Installations, both of them will provide team id, I think it is okey to have a getter here, it is only available when we are in a team context

2024-01-15 02:01 UTC, duanxianbo commented on src/components/pages/Marketplace/Modals/CreateAppVersionModal.component.tsx
> +                            label={'App Name'}
I will do this in a separate pr

2024-01-15 03:39 UTC, naturetime10 requested changes

2024-01-15 03:39 UTC, naturetime10 commented on src/storage/graph/team.node.ts
> +        return this.teamState.appInstallationIds?.map((appInstallationId) => {
Let's filter based on `installation.installedTeamId === this.teamState.id`, the do map.

2024-01-15 03:39 UTC, naturetime10 commented on src/storage/states/pluginApp.state.ts
> +        );
I feel a direct for loop may be more clear.

2024-01-15 03:39 UTC, naturetime10 commented on src/storage/states/pluginApp.state.ts
> +        const versions = json.Versions.reduce(
I feel a direct for loop maybe more clear

2024-01-15 04:09 UTC, duanxianbo commented on src/storage/graph/team.node.ts
> +        return this.teamState.appInstallationIds?.map((appInstallationId) => {
this will loop more items, right?

2024-01-16 01:38 UTC, naturetime10 approved these changes

2024-01-16 01:38 UTC, naturetime10 commented on src/storage/graph/team.node.ts
> +        }).filter(v => v) || [];
```suggestion
        }) || [];
```

2024-01-16 01:38 UTC, naturetime10 commented on src/storage/graph/team.node.ts
> +        return this.teamState.appInstallationIds?.map((appInstallationId) => {
You are right. Please ignore my comments.

2024-01-16 01:38 UTC, naturetime10 commented on src/storage/graph/team.node.ts
> +        }).filter(v => v) || [];
```suggestion
        }) || [];
```

2024-01-16 09:35 UTC, naturetime10 requested changes

2024-01-16 09:35 UTC, naturetime10 commented on src/storage/graph/team.node.ts
> +
```suggestion
```

2024-01-16 09:35 UTC, naturetime10 commented on src/storage/graph/team.node.ts
> +
```suggestion
```

2024-01-16 09:37 UTC, naturetime10 requested changes

2024-01-16 09:37 UTC, naturetime10 commented on src/storage/graph/app.node.ts
> +    public get latestVersionForTeam(): AppVersionNode | undefined {
Discussed offline. We will change this into a method which accepts `teamId` as parameter.

2024-01-19 05:59 UTC, naturetime10 requested changes

2024-01-19 05:59 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal.component.tsx
> +        return Boolean(this.state.app?.versions.some(
```suggestion
        return this.state.app?.versions.some((appVersion) => appVersion.number == versionNumber,
        )) || false;
```

2024-01-19 05:59 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal.component.tsx
> +        this.stateSyncer.deleteAppSecret(this.state.app!.id, secretId);
```suggestion
        return () =>
            this.stateSyncer.deleteAppSecret(this.state.app!.id, secretId);
```

2024-01-19 05:59 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal.component.tsx
> +        const latestVersionForTeam = this.graphSource.currentTeamAppVersion(
Let's use `latestVersionForTeam(this.localStore.currTeamId)`

2024-01-19 05:59 UTC, naturetime10 commented on src/storage/graph/app.node.ts
> +        return this.versions.find((version) => version.number === teamAppVersion.appVersion);
```suggestion
        }
        
        return this.versions.find((version) => version.number === teamAppVersion.appVersion);
```

2024-01-19 05:59 UTC, naturetime10 commented on src/storage/graph/appInstallation.node.ts
> +        debugger
```suggestion
```

2024-01-19 05:59 UTC, naturetime10 commented on src/storage/graph/appInstallation.node.ts
> +        debugger
```suggestion
```

2024-01-19 05:59 UTC, naturetime10 commented on src/storage/graph/graphSource.ts
> +
```suggestion
```

2024-01-19 05:59 UTC, naturetime10 commented on src/storage/states/pluginApp.state.ts
> +export class PluginAppState {
Can we rename this to `AppState` or at least `ThirdPartyAppState`?

2024-01-19 05:59 UTC, naturetime10 commented on src/storage/states/teamAppVersion.state.ts
> +
```suggestion
```

2024-01-19 05:59 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +    })
```suggestion
    });
```

2024-01-19 14:53 UTC, duanxianbo commented on src/storage/states/pluginApp.state.ts
> +export class PluginAppState {
we can raname to AppState but need to rename the file name to ThirdPartyAppState

2024-01-20 01:39 UTC, naturetime10 requested changes

2024-01-20 01:39 UTC, naturetime10 commented on src/entity/app.ts
> +    managedByTeam: Team;
Add `latestVersionForTeam()` function.

2024-01-20 01:39 UTC, naturetime10 commented on src/entity/appInstallation.ts
> +export interface AppInstallation {
`TeamAppInstallation`

2024-01-20 18:41 UTC, naturetime10 requested changes

2024-01-20 18:41 UTC, naturetime10 commented on src/client/entity/remoteRolloutActivator.ts
> +export interface RemoteRolloutActivator {
Maybe use union to combine 3 different activators into `RemoteRolloutActivator`?

2024-01-20 18:41 UTC, naturetime10 commented on src/client/entity/remoteRolloutVersionSelector.ts
> +export interface RemoteRolloutVersionSelector {
Maybe use union to combine 2 different version selectors into `RemoteRolloutVersionSelector`?

2024-01-20 18:41 UTC, naturetime10 commented on src/client/entity/remoteTeamGroup.ts
> +export interface RemoteTeamGroup {
Maybe use union to combine 2 different team groups into `RemoteTeamGroup`?

2024-01-20 18:41 UTC, naturetime10 commented on src/client/entity/remoteUserGroup.ts
> +export interface RemoteUserGroup {
Maybe use union to combine 2 different user groups into `RemoteUserGroup`?

2024-01-20 18:41 UTC, naturetime10 commented on src/components/pages/Marketplace/ManagedTab.component.tsx
> +                        const currentTeamAppVersion = app.latestVersionForTeam(this.graphSource.currentTeam()?.id)
const currTeamId = this.graphSource.currentTeam()?.id;
const teamAppVersion = app.latestVersionForTeam;

2024-01-20 18:41 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/CredentialTab.component.tsx
> +                console.log('[AppComponent] waiting for state changes');
```suggestion
                console.log('[CredentialTabComponent] waiting for state changes');
```

2024-01-20 18:41 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/CredentialTab.component.tsx
> +                });
```suggestion
 const tmpApiSecretInputs: Record<number, ApiSecretInput> =
                        {};

                    app?.secrets.forEach((secret) => {
                        tmpApiSecretInputs[secret.id] = {
                            name: secret.name,
                        };
                    });
                setApiSecretInputs(tmpApiSecretInputs);
```

2024-01-20 18:41 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/CredentialTab.component.tsx
> +    >({});
We need fill in initial value for `apiSecretInputs` first.

2024-01-20 18:41 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/CredentialTab.component.tsx
> +    }
```suggestion
```

2024-01-20 18:41 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/ManageAppModal.component.tsx
> +    app?: App,
```suggestion
    app?: App;
```

2024-01-20 18:41 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/ManageAppModal.component.tsx
> +        }
```suggestion
        const currTeamId = this.props.deps.graphSource.currentTeam()?.id;
        const latestTeamAppVersion = this.state.app?.latestVersionForTeam(currTeamId);
        if (!latestTeamAppVersion) {
           return null
        }
```

2024-01-20 18:41 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/RolloutsTab.component.tsx
> +            <CreateTeamRolloutModalComponent ref={createTeamRolloutModalRef} isValidVersionNumber={props.isValidVersionNumber} />
```suggestion
            <CreateTeamRolloutModalComponent 
                ref={createTeamRolloutModalRef} 
                isValidVersionNumber={props.isValidVersionNumber} />
```

2024-01-20 18:41 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/VersionsTab.component.tsx
> +        debugger
```suggestion
```

2024-01-20 18:41 UTC, naturetime10 commented on src/storage/graph/app.node.ts
> +                teamAppVersion.teamId === teamId && teamAppVersion.appId === this.app.id,
```suggestion
                teamAppVersion.teamId === teamId && 
                teamAppVersion.appId === this.app.id,
```

2024-01-20 18:41 UTC, naturetime10 commented on src/storage/states/app.state.ts
> +
```suggestion
```

2024-01-20 18:41 UTC, naturetime10 commented on src/storage/states/teamAppVersion.state.ts
> +export class TeamAppVersionState {
```suggestion
export class TeamAppInstallationState {
```

2024-01-20 18:41 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +
```suggestion
```

2024-01-20 22:10 UTC, duanxianbo commented on src/storage/states/teamAppVersion.state.ts
> +export class TeamAppVersionState {
it is team app version state

2024-01-20 22:29 UTC, duanxianbo commented on src/client/entity/remoteUserGroup.ts
> +export interface RemoteUserGroup {
maybe we should keep this in RemoteObj, but create different entity for local state, since I think this is only used to receive the backend obj and we should check the type anyway

2024-01-21 23:43 UTC, naturetime10 approved these changes

2024-01-22 00:27 UTC, merged