Integrate group and rollout
teamyapp/teamy-web pull request #550
Opened 2024-01-25 03:34 UTC by duanxianbo

[(task:19154)](https://staging.teamyapp.com/teams/107/tasks/19154)

2024-01-26 03:52 UTC, naturetime10 requested changes

2024-01-26 03:52 UTC, naturetime10 commented on src/storage/graph/activator.node.ts
> +
```suggestion
```

2024-01-26 03:52 UTC, naturetime10 commented on src/storage/graph/app.node.ts
> +
```suggestion
```

2024-01-26 03:52 UTC, naturetime10 commented on src/storage/graph/app.node.ts
> +
```suggestion
```

2024-01-26 03:52 UTC, naturetime10 commented on src/storage/graph/group.node.ts
> +
```suggestion
```

2024-01-26 03:52 UTC, naturetime10 commented on src/storage/states/app.state.ts
> +
```suggestion
```

2024-01-26 03:52 UTC, naturetime10 commented on src/storage/states/versionSelector.state.ts
> +
```suggestion
```

2024-01-26 05:21 UTC, naturetime10 requested changes

2024-01-26 05:21 UTC, naturetime10 commented on src/entity/group.ts
> +
```suggestion
```

2024-01-26 05:21 UTC, naturetime10 commented on src/entity/group.ts
> +
```suggestion
```

2024-01-26 05:21 UTC, naturetime10 commented on src/entity/rollout.ts
> +export interface TimeRangeActivator extends ActivatorInfo{
```suggestion
}

export interface TimeRangeActivator extends ActivatorInfo{
```

2024-01-26 05:21 UTC, naturetime10 commented on src/entity/rollout.ts
> +    type: 'STATIC' | 'EXPERIMENT';
VersionSelectorType

2024-01-26 05:21 UTC, naturetime10 commented on src/storage/graph/activator.node.ts
> +
```suggestion
```

2024-01-26 05:21 UTC, naturetime10 commented on src/storage/graph/activator.node.ts
> +    get type(): 'STATIC' | 'TIME_RANGE' | 'MAX_VIEWERS' | 'PERCENTAGE' {
Can we define type in entity?

2024-01-26 05:21 UTC, naturetime10 commented on src/storage/graph/app.node.ts
> +
```suggestion
```

2024-01-26 05:21 UTC, naturetime10 commented on src/storage/graph/group.node.ts
> +    public get type(): 'STATIC' | 'FILTER' {
Can we define type in entity?

2024-01-26 05:21 UTC, naturetime10 commented on src/storage/graph/group.node.ts
> +
```suggestion
```

2024-01-26 05:21 UTC, naturetime10 commented on src/storage/graph/rollout.node.ts
> +        | PercentageActivatorNode {
Can we have a union type called `ActivatorNode`?

2024-01-26 05:21 UTC, naturetime10 commented on src/storage/graph/versionSelector.node.ts
> +    get type(): 'STATIC' | 'EXPERIMENT' {
Can we define versionSelectorType in entity?

2024-01-27 01:12 UTC, naturetime10 requested changes

2024-01-27 01:12 UTC, naturetime10 commented on src/storage/states/group.state.ts
> +    public rolloutIds: number[],
Can we create rolloutGroupRelationState to support querying from group to rollout and rollout to group?

2024-01-27 01:26 UTC, naturetime10 requested changes

2024-01-27 01:26 UTC, naturetime10 commented on src/entity/rollout.ts
> -    groups: Group<GroupMember>[];
Can we add name and groups.

2024-01-27 01:26 UTC, naturetime10 commented on src/storage/graph/app.node.ts
> +
```suggestion
```

2024-01-27 01:26 UTC, naturetime10 commented on src/storage/states/versionSelector.state.ts
> +
```suggestion
```

2024-01-27 01:26 UTC, naturetime10 commented on src/storage/states/versionSelector.state.ts
> +
```suggestion
```

2024-01-27 01:58 UTC, duanxianbo commented on src/entity/rollout.ts
> -    groups: Group<GroupMember>[];
added

2024-01-27 01:59 UTC, duanxianbo commented on src/storage/states/group.state.ts
> +    public rolloutIds: number[],
will do in next pr

2024-01-27 02:02 UTC, naturetime10 approved these changes

2024-01-27 02:02 UTC, naturetime10 commented on src/storage/graph/rollout.node.ts
> +
```suggestion

```

2024-01-27 02:04 UTC, merged