Fix create rollout + group + update
teamyapp/teamy-web pull request #556
Opened 2024-02-11 16:02 UTC by duanxianbo

[(task:19552)](https://staging.teamyapp.com/teams/107/tasks/19552)

2024-02-11 16:03 UTC, duanxianbo commented on src/storage/syncer/stateMutators.ts
> +
```suggestion
```

2024-02-11 18:48 UTC, naturetime10 requested changes

2024-02-11 18:48 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/CreateRolloutView.component.tsx
> +        && !this.state.experimentVersionSelectorInput?.versionNumbers?.length) {
Can we separate null check for `this.state.experimentVersionSelectorInput?.versionNumbers` and checking it's `length`?

2024-02-11 18:48 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/EditRolloutView.component.tsx
> +                if (!staticVersionSelectorInput?.versionNumber && !experimentVersionSelectorInput?.versionNumbers.length) {
Can we separate null check for `this.state.experimentVersionSelectorInput?.versionNumbers` and checking it's `length`?

2024-02-11 18:48 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/RolloutsTab.component.tsx
>      ) => {
Can include return type here?

2024-02-11 18:48 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/RolloutsTab.component.tsx
>      ) => {
Can include return type here?

2024-02-12 00:53 UTC, naturetime10 requested changes

2024-02-12 00:53 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +        })
Can we extract this into variable?

2024-02-12 01:05 UTC, naturetime10 approved these changes

2024-02-12 01:05 UTC, merged