Fix create and update appVersion
teamyapp/teamy-web pull request #561
Opened 2024-02-24 03:29 UTC by duanxianbo

[(task:19803)](https://staging.teamyapp.com/teams/107/tasks/19803)

2024-02-24 10:52 UTC, naturetime10 requested changes

2024-02-24 10:52 UTC, naturetime10 commented on src/client/appVersion.client.ts
> +                            number
```suggestion
                            number
                            locked
```

2024-02-24 10:52 UTC, naturetime10 commented on src/client/appVersion.client.ts
> +                            changes
Is this a single item or a list?
```
GraphQL requires developer to specify the internal field when accessing list from backend.
```

2024-02-24 10:52 UTC, naturetime10 commented on src/client/entity/remoteAppVersion.ts
> +    errorMessage?: string;
```suggestion
    errorMessage?: string;
    app: RemoteApp;
```

2024-02-24 10:52 UTC, naturetime10 commented on src/client/file.client.ts
> +        return `${this.cloudWebAPIEndpoint}/file/download-folder?path=${encodedFilePath}`;
```suggestion
        return `${this.cloudWebAPIEndpoint}/file/download?path=${encodedFilePath}`;
```

2024-02-24 10:52 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/VersionsTab.component.tsx
> +    ]);
```suggestion
    }, []);
```

2024-02-24 10:52 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/VersionsTab.component.tsx
> +    const handleAppVersionFileChange = async (
```suggestion
    const onAppVersionFileChange = async (
```

2024-02-24 10:52 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/VersionsTab.component.tsx
> +            alert('Fail to upload file');
I wonder when does this happen?

2024-02-24 10:52 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/VersionsTab.component.tsx
> +        } else {
```suggestion
        }
```

2024-02-24 10:52 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/VersionsTab.component.tsx
> +        }
```suggestion
```

2024-02-24 10:52 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/VersionsTab.component.tsx
> +                                href={props.deps.fileClient.getRemoteFolderDownloadUrl(
```suggestion
                                href={props.deps.fileClient.getDownloadUrl(
```

2024-02-24 10:52 UTC, naturetime10 commented on src/entity/input.ts
> +
```suggestion
```

2024-02-24 10:52 UTC, naturetime10 commented on src/libs/ui/LinkButton.tsx
> +export const LinkButtonUI = ({label, href, target}: Props) => {
Can we directly embed link without creating a new component?

2024-02-24 10:52 UTC, naturetime10 commented on src/libs/ui/LinkButton.module.scss
Remove this.

2024-02-24 10:52 UTC, naturetime10 commented on src/entity/appVersion.ts
> +    iconPath: string;
```suggestion
    iconPath(size: number): string;
```

2024-02-24 10:52 UTC, naturetime10 commented on src/storage/graph/appVersion.node.ts
> +    public get iconPath(): string {
```suggestion
    public get iconPath(size: number): string {
```

2024-02-24 10:52 UTC, naturetime10 commented on src/storage/graph/appVersion.node.ts
> +const APP_VERSION_ICON_NAME = '100x100.jpg';
```suggestion
```

2024-02-24 10:52 UTC, naturetime10 commented on src/storage/graph/appVersion.node.ts
> +       return `files/apps/${this.appVersion.appId}/${this.appVersion.number}/icons/${APP_VERSION_ICON_NAME}`;
```suggestion
       return `files/apps/${this.appVersion.appId}/${this.appVersion.number}/icons/${size}.png`;        
```

2024-02-24 10:52 UTC, naturetime10 commented on src/storage/graph/appVersion.node.ts
> +
```suggestion
```

2024-02-24 10:52 UTC, naturetime10 commented on src/storage/graph/appVersion.node.ts
> +        return `files/apps/${this.appVersion.appId}/${this.appVersion.number}/`;
Is the last `/` needed?

2024-02-24 10:52 UTC, naturetime10 commented on src/storage/states/appVersion.state.ts
> +
```suggestion
```

2024-02-24 10:52 UTC, naturetime10 commented on src/storage/states/appVersion.state.ts
> +export class AppVersionPriceState {
Can we move this to a different file?

2024-02-24 10:52 UTC, naturetime10 commented on src/storage/states/appVersion.state.ts
> +
```suggestion
```

2024-02-24 10:52 UTC, naturetime10 commented on src/storage/states/appVersion.state.ts
> +export class AppVersionChangeState {
Can we move this to a different file?

2024-02-24 10:52 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +        case 'Create':
This may need to be fill in when other people created a new version.

2024-02-24 10:52 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +            break;
This may need to be fill in when other people deleted a version.

2024-02-24 10:52 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +                appVersionPrice.price === price.amount
```suggestion
```

2024-02-24 10:52 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +        currAppState.appVersionPrices.push({
Need to replace existing price or add new price.

2024-02-24 10:52 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +        });
Need to replace existing change or add new change.

2024-02-24 10:52 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +    change: string,
Should we pass in `Change` entity? It will have `change` and `change ID`

2024-02-24 10:52 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +
```suggestion
```

2024-02-24 15:42 UTC, duanxianbo commented on src/client/appVersion.client.ts
> +                            changes
it is a list of string, so we are good

2024-02-24 15:45 UTC, duanxianbo commented on src/components/pages/Marketplace/Modals/ManageAppModal/VersionsTab.component.tsx
> +    ]);
we can not do that, this useEffect depends on selectedVersion,  selectedVersion can change means user can select other version, we can not watch selectedAppVersion directly neither, since it is from a getter object

2024-02-24 15:55 UTC, duanxianbo commented on src/storage/graph/appVersion.node.ts
> +        return `files/apps/${this.appVersion.appId}/${this.appVersion.number}/`;
no

2024-02-24 15:56 UTC, duanxianbo commented on src/storage/syncer/stateMutators.ts
> +            break;
right, but I guess we can make this in other prs, I think only update is mandatory for this pr

2024-02-24 15:57 UTC, duanxianbo commented on src/storage/syncer/stateMutators.ts
> +        case 'Create':
right, but I guess we can make this in other prs, I think only update is mandatory for this pr for uploading package flow

2024-02-24 15:58 UTC, duanxianbo commented on src/storage/syncer/stateMutators.ts
> +    change: string,
we do not get change id from backend gql, changes is just a list of strings on appversion

2024-02-24 16:00 UTC, duanxianbo commented on src/storage/syncer/stateMutators.ts
> +        });
I think if we want to replace changes, we should change the gql model and include change id

2024-02-24 16:09 UTC, duanxianbo commented on src/storage/syncer/stateMutators.ts
> +        currAppState.appVersionPrices.push({
I think we are agreed that for a group of appid, versionnumber, currency will correspond only one amount, is that still valid?  price table does not have id

2024-02-24 19:21 UTC, naturetime10 requested changes

2024-02-24 19:21 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +        currAppState.appVersionPrices.push({
The `key` should be `appId, versionNumber, currency`. We can use those to replace price.

2024-02-24 19:21 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +    change: string,
Can we get change ID from backend?

2024-02-24 19:21 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +        });
Let's include change ID to enforce the consistent `update` semantic.

2024-02-24 19:23 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/VersionsTab.component.tsx
> +    ]);
Why can't we watch `selectedVersion` directly?

2024-02-24 19:53 UTC, duanxianbo commented on src/components/pages/Marketplace/Modals/ManageAppModal/VersionsTab.component.tsx
> +    ]);
Because we get the selected version from a getter, that means each evaluation, we get a new object anyway, then we run into infinite calling problems

2024-02-25 02:10 UTC, duanxianbo commented on src/components/pages/Marketplace/Modals/ManageAppModal/VersionsTab.component.tsx
> +            alert('Fail to upload file');
uploadFile function handle and produces error

2024-02-25 07:09 UTC, naturetime10 requested changes

2024-02-25 07:09 UTC, naturetime10 commented on src/client/file.client.ts
> +    public getRemoteFolderDownloadUrl(filePath: string): string {
```suggestion
    public getRemoteDownloadUrl(filePath: string): string {
```

2024-02-25 07:09 UTC, naturetime10 commented on src/client/entity/remoteAppVersion.ts
> +export type RemoteAppVersionStatus = 'INIT' | 'UPLOADING' | 'PROCESSING' | 'READY' | 'ERROR';
```suggestion
export type RemoteAppVersionStatus = 
    'INIT' | 
    'UPLOADING' | 
    'PROCESSING' | 
    'READY' | 
    'ERROR';
```

2024-02-25 07:09 UTC, naturetime10 commented on src/entity/appVersion.ts
> +export type AppVersionStatus = 'INIT' | 'UPLOADING' | 'PROCESSING' | 'READY' | 'ERROR';
```suggestion
export type AppVersionStatus = 
    'INIT' | 
    'UPLOADING' | 
    'PROCESSING' | 
    'READY' | 
    'ERROR';
```

2024-02-25 07:09 UTC, naturetime10 commented on src/storage/graph/appVersion.node.ts
> +            if (appState.appVersionChanges[changeId].versionNumber === this.appVersion.number &&
```suggestion
            if ((appState.appVersionChanges[changeId].versionNumber === this.appVersion.number ) &&
```

2024-02-25 07:09 UTC, naturetime10 commented on src/storage/graph/appVersion.node.ts
> +                appState.appVersionChanges[changeId].appId === this.appVersion.appId) {
```suggestion
                (appState.appVersionChanges[changeId].appId === this.appVersion.appId)) {
```

2024-02-25 07:09 UTC, naturetime10 commented on src/storage/states/appVersion.state.ts
> +export type AppVersionStatus = 'INIT' | 'UPLOADING' | 'PROCESSING' | 'READY' | 'ERROR';
```suggestion
export type AppVersionStatus = 
    'INIT' | 
    'UPLOADING' | 
    'PROCESSING' | 
    'READY' | 
    'ERROR';
```

2024-02-25 07:09 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +
```suggestion
```

2024-02-25 07:09 UTC, naturetime10 approved these changes

2024-02-25 18:08 UTC, merged