Integrate 3rd party apps
teamyapp/teamy-web pull request #563
Opened 2024-02-27 03:27 UTC by duanxianbo

[(task:19912)](https://staging.teamyapp.com/teams/107/tasks/19912)

2024-02-27 10:08 UTC, naturetime10 requested changes

2024-02-27 10:08 UTC, naturetime10 commented on src/components/pages/Marketplace/DiscoverTab.component.tsx
> +    private handleAppInstallBtnClicked = (
```suggestion
    private onInstallAppButtonClicke = (
```

2024-02-27 10:08 UTC, naturetime10 commented on src/components/pages/Marketplace/DiscoverTab.component.tsx
> +    private handleAppRemoveBtnClicked = (
```suggestion
    private onRemoveAppButtonClick = (
```

2024-02-27 10:08 UTC, naturetime10 commented on src/components/pages/Marketplace/FilterTab.component.tsx
> +    private handleAppInstallBtnClicked = (
```suggestion
    private onInstallAppButtonClick = (
```

2024-02-27 10:08 UTC, naturetime10 commented on src/components/pages/Marketplace/FilterTab.component.tsx
> +    private handleAppRemoveBtnClicked = (
```suggestion
    private onRemoveAppButtonClick = (
```

2024-02-27 10:08 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/AppSettingModal.component.tsx
>  };
This need to integrate with backend.

2024-02-27 10:08 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/AppSettingModal.component.tsx
> +                    !(this.contentRef.current instanceof Element)
```suggestion
                if (!this.contentRef.current)
```

2024-02-27 10:08 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/VersionsTab.component.tsx
> +import { APP_VERSION_ICON_SIZE } from '@core/storage/graph/appVersion.node';
I think we should define `APP_VERSION_ICON_SIZE` in the UI component. It's directly related to view instead of data itself.

2024-02-27 10:08 UTC, naturetime10 commented on src/entity/money.ts
> +    return 'USD';
Can we add TODO to get this through backend Geo API?

2024-02-27 10:08 UTC, naturetime10 commented on src/storage/graph/appVersion.node.ts
> +export const APP_VERSION_ICON_SIZE = 100;
```suggestion
```

2024-02-27 10:08 UTC, naturetime10 commented on src/storage/graph/graphSource.ts
> +            const app = appState.apps[appId];
```suggestion
```

2024-02-27 10:08 UTC, naturetime10 commented on src/storage/graph/graphSource.ts
> +        const appState = this.localStore.getState();
Maybe we can add a helper called `apps` to get a list of apps?

2024-02-27 10:08 UTC, naturetime10 commented on src/storage/graph/graphSource.ts
> +        for (const appId in appState.apps) {
I think we can do a `filter` and `map`?

2024-02-28 00:05 UTC, duanxianbo commented on src/storage/graph/graphSource.ts
> +        for (const appId in appState.apps) {
I do not think that works on a Record object

2024-02-28 07:56 UTC, naturetime10 requested changes

2024-02-28 07:56 UTC, naturetime10 commented on src/storage/syncer/stateSyncer.ts
> +        team.appInstallationIds = team.appInstallationIds?.filter(installationId => installationId !== installation.id);
I think we should consider splitting `[]TeamAppInstallation` into a separate state instead of keeping partial data in `app.installationIds` and `team.appInstallationIds`.

2024-02-28 07:56 UTC, naturetime10 commented on src/storage/graph/graphSource.ts
> +        for (const appId in appState.apps) {
@duanxianbo I see.

2024-02-28 10:42 UTC, duanxianbo commented on src/storage/syncer/stateSyncer.ts
> +        team.appInstallationIds = team.appInstallationIds?.filter(installationId => installationId !== installation.id);
They are separated, we have separate state team app installations in global state, installationids in team state and installationids in app state, yesterday I was trying to remove those installation ids in app and team states, but then I realize we did this because maybe we want to quickly find installations that related to the team or app, those installation ids are filtered in backend graphql

2024-02-29 02:39 UTC, naturetime10 requested changes

2024-02-29 02:39 UTC, naturetime10 commented on src/components/pages/Marketplace/Modals/ManageAppModal/VersionsTab.component.module.scss
> +
```suggestion
```

2024-02-29 02:39 UTC, naturetime10 commented on src/entity/money.ts
> +    // TODO: Implement logic to get the local currency
```suggestion
    // TODO: Get local currency using IP address
```

2024-02-29 02:39 UTC, naturetime10 approved these changes

2024-02-29 02:42 UTC, merged