Create and delete project
teamyapp/teamy-web pull request #581
Opened 2024-03-25 02:23 UTC by duanxianbo

[(task:20580)](https://staging.teamyapp.com/teams/107/tasks/20580)

2024-03-25 02:25 UTC, duanxianbo commented on src/client/entity/input.ts
> +
```suggestion
```

2024-03-25 02:25 UTC, duanxianbo commented on src/components/pages/Planning/Projects.component.tsx
> +    // }
```suggestion
```

2024-03-25 02:25 UTC, duanxianbo commented on src/components/pages/Planning/Projects.component.tsx
> +    // const rows: Row[] = []
```suggestion
```

2024-03-25 02:25 UTC, duanxianbo commented on src/entity/input.ts
> +
```suggestion
```

2024-03-25 09:31 UTC, naturetime10 requested changes

2024-03-25 09:31 UTC, naturetime10 commented on src/client/project.client.ts
> +
```suggestion
```

2024-03-25 09:31 UTC, naturetime10 commented on src/client/project.client.ts
> +                    }
Should we move this into `.graphql`?

2024-03-25 09:31 UTC, naturetime10 commented on src/components/pages/Planning/Planning.component.tsx
>      }
Should this be moved into use effect and listen to state change?

2024-03-25 09:31 UTC, naturetime10 commented on src/components/pages/Planning/Project.component.tsx
> +        const ref = createRef<HTMLDivElement>();
Is this ref still being used?

2024-03-25 09:31 UTC, naturetime10 commented on src/components/pages/Planning/Project.component.tsx
> +    const rows: Row[] = props.project.phases.map((phase, index) => {
Can we move this after `useEffect`?

2024-03-25 09:31 UTC, naturetime10 commented on src/components/pages/Planning/Projects.component.tsx
>  } from './Timeline.component';
```suggestion
import {
    Row,
    TimelineComponent,
    TimelineComponentHandle,
} from './Timeline.component';
import styles from './Projects.component.module.scss';
```

2024-03-25 09:31 UTC, naturetime10 commented on src/components/pages/Planning/Projects.component.tsx
> +    }
Can we move this into the `return` statement?

2024-03-25 09:31 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +            toDate(remoteProject.actualStartAt) ||
We need to check `undefined` because `actualStartAt` can be `null`.

2024-03-25 09:31 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +            toDate(remoteProject.actualEndAt) || localOldProject.actualEndAt,
We need to check `undefined` because `actualEndAt` can be `null`.

2024-03-25 09:31 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +        actualStartAt:
We need to check `undefined` because `actualStartAt` can be `null`.

2024-03-25 09:31 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +            toDate(remotePhase.actualEndAt) || localOldPhase.actualEndAt,
We need to check `undefined` because `actualEndAt` can be `null`.

2024-03-26 00:29 UTC, naturetime10 approved these changes

2024-03-26 00:29 UTC, naturetime10 commented on src/components/pages/Planning/Planning.component.tsx
>  import { StoryComponent } from './Story.component';
```suggestion
import { ProjectComponent } from './Project.component';
import { ProjectsComponent } from './Projects.component';
import { StoryComponent } from './Story.component';
import styles from './Planning.component.module.scss';
```

2024-03-26 02:42 UTC, merged