Update team group name
teamyapp/teamy-web pull request #656
Opened 2024-04-30 09:45 UTC by duanxianbo

<img width="977" alt="image" src="https://github.com/teamyapp/teamy-web/assets/6356492/00a6eed4-e805-48f4-8381-80d932a3752a">

[(task:21559)](https://staging.teamyapp.com/teams/107/tasks/21559)

<img width="998" alt="image" src="https://github.com/teamyapp/teamy-web/assets/6356492/14d03a7d-2771-4262-a946-38cee462e7cd">

<img width="967" alt="image" src="https://github.com/teamyapp/teamy-web/assets/6356492/8bc22cf2-519b-4647-843e-094d4fe596d7">

I got some issue to make the input to fit the content

2024-05-01 05:22 UTC, naturetime10 commented
Can we make text input background transparent and increase text input height? Can we use red `cross` mark instead of cross mark with circular background?

2024-05-11 00:45 UTC, naturetime10 commented
Can we update the screenshot? Thanks!

2024-05-11 00:54 UTC, duanxianbo commented
> Can we update the screenshot? Thanks!

I am having some issue to make the input to fit the content size 
<img width="967" alt="image" src="https://github.com/teamyapp/teamy-web/assets/6356492/3636ea86-cb50-4b6d-9760-6ae6460656c0">

2024-05-11 23:43 UTC, naturetime10 requested changes

2024-05-11 23:43 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +                            {!isEditing ? (
Can we change `!isEditing` to `isEditing` and swap the order of 
```
<div
                                    className={`${styles.Name} ${classNames({
                                        [styles.HasAction]: groupId,
                                    })}`}
                                    onDoubleClick={this.handleTeamMemberGroupNameClicked(
                                        groupName,
                                        groupId,
                                    )}
                                >
                                    {groupName}
                                </div>
```
and
```
<div
                                    className={`${styles.Name} ${classNames({
                                        [styles.HasAction]: groupId,
                                    })}`}
                                    onDoubleClick={this.handleTeamMemberGroupNameClicked(
                                        groupName,
                                        groupId,
                                    )}
                                >
                                    {groupName}
                                </div>
```

2024-05-11 23:43 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +                                    onInput={this.handleTeamMemberGroupNameChanged(
```suggestion
                                    onInput={this.handleTeamMemberGroupNameInput(
```

2024-05-11 23:43 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +    private handleTeamMemberGroupNameClicked =
```suggestion
    private handleOnTeamMemberGroupNameClick =
```

2024-05-11 23:43 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +    private handleTeamMemberGroupNameChanged =
```suggestion
    private handleTeamMemberGroupNameInput =
```

2024-05-11 23:43 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +        (groupId: number) => (event: ChangeEvent<HTMLDivElement>) => {
Can we update the data type for `event`?

2024-05-11 23:48 UTC, naturetime10 approved these changes
Approved with a few clean up comments

2024-05-12 01:12 UTC, merged