Add delete team member group confirm modal
teamyapp/teamy-web pull request #665
Opened 2024-05-23 01:54 UTC by duanxianbo

[(task:21714)](https://staging.teamyapp.com/teams/107/tasks/21714)

<img width="996" alt="image" src="https://github.com/teamyapp/teamy-web/assets/6356492/bb232f4b-f6fe-4664-b1d8-259a174fa61b">

2024-05-24 05:21 UTC, naturetime10 requested changes

2024-05-24 05:21 UTC, naturetime10 commented on src/components/internal/Modals/ConfirmActionsModal.component.module.scss
> +        -webkit-box-orient: vertical;
Can we just limit the height and use overflow hidden?

2024-05-24 05:21 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +                        message={`Do you want to delete this team member group ${this.state.deletingGroupName}?`}
I wonder whether we can make this modal to accept `content` with `ReactElement` type instead of `message` with `string` type for more flexible content?

2024-05-25 00:50 UTC, duanxianbo commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +                        message={`Do you want to delete this team member group ${this.state.deletingGroupName}?`}
we could, but currently we only have string to prop, we can change that in the future

2024-05-25 01:01 UTC, naturetime10 approved these changes

2024-05-25 01:01 UTC, naturetime10 commented on src/components/internal/Modals/ConfirmActionsModal.component.module.scss
> +        text-overflow: ellipsis;
```suggestion
```

2024-05-25 01:50 UTC, merged