Add and remove invitation to and from group
teamyapp/teamy-web pull request #679
Opened 2024-06-01 21:18 UTC by duanxianbo

<img width="962" alt="image" src="https://github.com/teamyapp/teamy-web/assets/6356492/39f01911-d9f6-4b1f-8d9b-a98430744311">

<img width="664" alt="image" src="https://github.com/teamyapp/teamy-web/assets/6356492/7416ca2d-ebeb-48c4-a5b8-89e310d38069">

updated:

<img width="1079" alt="image" src="https://github.com/teamyapp/teamy-web/assets/6356492/d398eae6-333f-464f-a6ed-8db7ae35868e">

2024-06-01 22:27 UTC, naturetime10 requested changes

2024-06-01 22:27 UTC, naturetime10 commented on src/client/graphql/fragment/invitation.graphql
> +
```suggestion
```

2024-06-01 22:27 UTC, naturetime10 commented on src/client/graphql/fragment/invitation.graphql
> +	receiverEmail
```suggestion
    receiverLastName
    receiverEmail
```

2024-06-01 22:27 UTC, naturetime10 commented on src/client/invitation.client.ts
> +import { print } from 'graphql';
I think this should be put above all other imports.

2024-06-01 22:27 UTC, naturetime10 commented on src/client/invitation.client.ts
> +
```suggestion
```

2024-06-01 22:27 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.module.scss
> +
```suggestion
```

2024-06-01 22:27 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.module.scss
> +
```suggestion
```

2024-06-01 22:27 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +import { SelectEntityPopupComponent } from '../SelectEntityPopupComponent.component';
```suggestion
import { SelecItemPopupComponent } from '../SelectItemPopupComponent.component';
```

2024-06-01 22:27 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +            (this.state.selectedGroupInvitations[group.id]?.size || 0);
Can we use a separate variables for those 2 sizes?

2024-06-01 22:27 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +                                <SelectEntityPopupComponent
```suggestion
                                <SelectItemPopupComponent
```

2024-06-01 22:27 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +                                                </>
Maybe use a separate function?

2024-06-01 22:27 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +        const allNonAcceptedInvitations = this.state.invitations.filter(
```suggestion
        const allNotAcceptedInvitations = this.state.invitations.filter(
```

2024-06-01 22:27 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +        const allNonAcceptedInvitations = this.state.invitations.filter(
I think we should use pending invitation instead. If invitation is declined, hide from this list.

2024-06-01 22:27 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +
```suggestion
```

2024-06-01 22:27 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +
```suggestion
```

2024-06-01 22:27 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +
```suggestion
```

2024-06-01 22:27 UTC, naturetime10 commented on src/components/internal/SelectEntityPopupComponent.component.module.scss
> +.Entities {
```suggestion
.Items {
```

2024-06-01 22:27 UTC, naturetime10 commented on src/components/internal/SelectEntityPopupComponent.component.tsx
> +import styles from './SelectEntityPopupComponent.component.module.scss';
```suggestion
import styles from './SelectItemPopupComponent.component.module.scss';
```

2024-06-01 22:27 UTC, naturetime10 commented on src/components/internal/SelectEntityPopupComponent.component.tsx
> +import styles from './SelectEntityPopupComponent.component.module.scss';
Can we move this after line 4?

2024-06-01 22:27 UTC, naturetime10 commented on src/components/internal/SelectEntityPopupComponent.component.tsx
> +    objectList: (closeContainer: () => void) => JSX.Element;
```suggestion
    items: (closeContainer: () => void) => ReactElement;
```

2024-06-01 22:27 UTC, naturetime10 commented on src/components/internal/SelectEntityPopupComponent.component.tsx
> +                    <div className={styles.Entities}>
```suggestion
                    <div className={styles.Items}>
```

2024-06-01 22:27 UTC, naturetime10 commented on src/components/internal/SelectEntityPopupComponent.component.tsx
> +                        <div className={styles.EntityList}>
```suggestion
                        <div className={styles.Items}>
```

2024-06-01 22:27 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
>  import styles from './Sprints.component.module.scss';
Can we move this after line 49?

2024-06-01 22:27 UTC, naturetime10 commented on src/components/pages/Sprints.component.tsx
> +                                        <SelectEntityPopupComponent
```suggestion
                                        <SelectItemPopupComponent
```

2024-06-01 22:27 UTC, naturetime10 commented on src/storage/graph/teamMemberGroup.node.ts
> +            .filter((invitation) => invitation.status !== 'ACCEPTED');
```suggestion
            .filter((invitation) => invitation.status === 'PENDING');
```

2024-06-01 22:27 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +
```suggestion
```

2024-06-01 22:27 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +
```suggestion
```

2024-06-01 22:27 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +                        teamMemberGroupId &&
```suggestion
                    teamMemberGroupInvitationRelation.groupId === teamMemberGroupId &&
```

2024-06-01 22:27 UTC, naturetime10 commented on src/storage/syncer/stateMutators.ts
> +                        invitationId
```suggestion
                    teamMemberGroupInvitationRelation.invitationId === invitationId
```

2024-06-02 03:47 UTC, naturetime10 requested changes

2024-06-02 03:47 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +
```suggestion
```

2024-06-02 18:39 UTC, naturetime10 commented
Forgot to push some commits? Can we add a new screenshot for the user list popup?

2024-06-02 19:16 UTC, duanxianbo commented
> Forgot to push some commits? Can we add a new screenshot for the user list popup?

done

2024-06-04 01:08 UTC, naturetime10 approved these changes

2024-06-04 01:08 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.module.scss
> +.InvitationProfile {
```suggestion

.InvitationProfile {
```

2024-06-04 01:08 UTC, naturetime10 commented on src/client/invitation.client.ts
> +import { print } from 'graphql';
Can we move this above line 1?

2024-06-04 01:08 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +        );
```suggestion
        const allPendingInvitations = this.state.invitations.filter(
            (invitation) => invitation.status === 'PENDING',
        );
```

2024-06-04 01:08 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +                        allNotAcceptedInvitations,
```suggestion
                        allPendingInvitations,
```

2024-06-04 01:08 UTC, naturetime10 commented on src/components/internal/Modals/TeamSettingsModal.component.tsx
> +                            allNotAcceptedInvitations,
```suggestion
                            allPendingInvitations,
```

2024-06-04 01:18 UTC, naturetime10 approved these changes

2024-06-04 01:18 UTC, naturetime10 commented on src/client/invitation.client.ts
> +
```suggestion
```

2024-06-04 01:23 UTC, merged