Allow users to preview image in attachment list in the task detail modal
teamyapp/teamy-web pull request #696
Opened 2024-07-05 17:52 UTC by Travisliang001

# Preview Image Demo
![image](https://github.com/teamyapp/teamy-web/assets/26618651/0269b997-ade1-4e7d-b616-de00803ed0f7)
![image](https://github.com/teamyapp/teamy-web/assets/26618651/db76dab3-dbbd-43e9-8354-23b2a589e021)

[(task:23035)](https://staging.teamyapp.com/teams/107/tasks/23035)
# Scope

- Allow users to preview attachments(image only)
- The icons in the list are hoverable and indicate they are clickable for previewing content.
- Set a fixed size for the preview window; if the image exceeds this size, enable scrolling within the preview window.

2024-07-05 20:37 UTC, duanxianbo commented on src/components/internal/Modals/TaskDetailModal.component.tsx
> +                    attachmentUrl={this.state?.previewAttachmentUrl}
```suggestion
                    attachmentUrl={this.state.previewAttachmentUrl}
```

2024-07-05 20:37 UTC, duanxianbo commented on src/components/internal/PreviewAttachment.component.tsx
> +        </ModalUI>
can we format this?

2024-07-05 20:39 UTC, duanxianbo commented on src/components/internal/Modals/TaskDetailModal.component.tsx
> +                    attachmentUrl={this.state?.previewAttachmentUrl}
I think this component may be better to live within AttachmentList

2024-07-05 20:40 UTC, duanxianbo commented
will we create button to allow user to go next and prev previews?

2024-07-05 23:44 UTC, duanxianbo commented on src/components/internal/PreviewAttachment.component.tsx
> +        </ModalUI>
yarn format

2024-07-06 02:24 UTC, naturetime10 requested changes

2024-07-06 02:24 UTC, naturetime10 commented on src/components/internal/Modals/TaskDetailModal.component.tsx
> +                    attachmentUrl={this.state?.previewAttachmentUrl}
Can we pass in `attachmentUrl` and `attachmentType` through `open` method of `previewAttachmentModalRef`?

2024-07-06 02:24 UTC, naturetime10 commented on src/components/internal/Modals/TaskDetailModal.component.tsx
> +    private onPreviewAttachmentClick = (url: string) => {
```suggestion
    private onPreviewAttachmentClick = (attachmentType: AttachmentType, url: string) => {
```

2024-07-06 02:24 UTC, naturetime10 commented on src/components/internal/Modals/TaskDetailModal.component.tsx
> +        });
```suggestion
```

2024-07-06 02:24 UTC, naturetime10 commented on src/components/internal/Modals/TaskDetailModal.component.tsx
> +        this.previewAttachmentModalRef.current?.open();
```suggestion
        this.previewAttachmentModalRef.current?.open(attachmentType, url);
```

2024-07-06 02:24 UTC, naturetime10 commented on src/components/internal/PreviewAttachment.component.module.scss
Can we rename `PreviewAttachmentModal.component.module.scss`.

2024-07-06 02:24 UTC, naturetime10 commented on src/components/internal/PreviewAttachment.component.tsx
> +
```suggestion
```

2024-07-06 02:24 UTC, naturetime10 commented on src/components/internal/PreviewAttachment.component.tsx
Can we rename this file to `src/components/internal/PreviewAttachmentModal.component.tsx` and move into `Modals`?

2024-07-06 02:24 UTC, naturetime10 commented on src/components/internal/PreviewAttachment.component.tsx
> +                Image Preview
```suggestion
               Preview Attachment
```

2024-07-06 02:24 UTC, naturetime10 commented on src/components/internal/PreviewAttachment.component.tsx
> +                <img src={props.attachmentUrl} alt="Preview" />
Do we want make preview image only or any attachment?

2024-07-06 02:24 UTC, naturetime10 commented on src/libs/ui/AttachmentList.tsx
> +                            <div className={styles.LeftSection} onClick={handlePreviewAttachment(attachment.url)}>
```suggestion
                            <div className={styles.LeftSection} 
                            onClick={handlePreviewAttachment(attachment.url, attachment.type)}>
```

2024-07-06 02:24 UTC, naturetime10 commented on src/libs/ui/MarkdownEditor.tsx
> +    onPreviewAttachment: (url: string) => void;
```suggestion
    onPreviewAttachment: (attachmentType: AttachmentType, url: string) => void;
```

2024-07-06 02:26 UTC, naturetime10 commented
> will we create button to allow user to go next and prev previews?

https://fonts.google.com/icons?selected=Material+Symbols+Outlined:arrow_back_ios:FILL@1;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%235f6368

https://fonts.google.com/icons?selected=Material+Symbols+Outlined:arrow_back_ios:FILL@1;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%235f6368

2024-07-06 03:10 UTC, naturetime10 requested changes

2024-07-06 03:10 UTC, naturetime10 commented on src/components/internal/Modals/TaskDetailModal.component.tsx
>      }
```suggestion
    }
    
```

2024-07-06 07:20 UTC, naturetime10 requested changes

2024-07-06 07:20 UTC, naturetime10 commented on src/libs/ui/AttachmentList.tsx
> +    onPreviewAttachment: (url: string) => void;
```suggestion
    relativeLayout: RelativeLayout;
    onDeleteAttachment?: (attachmentId: number) => void;
    onCopyAttachmentLink?: (url: string) => void;
    onPreviewAttachment?: (url: string) => void;
```

2024-07-07 04:03 UTC, Travisliang001 commented
> will we create button to allow user to go next and prev previews?

will create separate PR for this

2024-07-07 04:08 UTC, naturetime10 approved these changes

2024-07-07 04:08 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +            previewAttachmentType: '',
```suggestion
```

2024-07-07 04:08 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +    constructor(props: Props) {
```suggestion

    constructor(props: Props) {
```

2024-07-07 04:08 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +                    />
Can we extract this to a separate function and put switch case inside and switch on `previewAttachmentType`?

2024-07-07 04:08 UTC, naturetime10 commented on src/libs/ui/AttachmentList.module.scss
> +                cursor: pointer;
```suggestion
                cursor: pointer;
                
```

2024-07-07 04:08 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.module.scss
> +    min-height: 300px; /* Minimum height for the container */
Just curious, what's the reason for for min width and min hight? Is this for modal title and close button to be render without issue?

2024-07-07 04:08 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.module.scss
> +    overflow: auto; /* Enable scrolling */
```suggestion
    overflow: auto;
```

2024-07-07 04:08 UTC, naturetime10 commented on src/libs/ui/AttachmentList.tsx
> +        }
```suggestion
        props.onDeleteAttachment?.call(null, attachmentId);
```

2024-07-07 04:08 UTC, naturetime10 commented on src/libs/ui/AttachmentList.tsx
> +        }
```suggestion
        props.onCopyAttachmentLink?.call(null, url);
```

2024-07-07 04:24 UTC, Travisliang001 commented on src/components/internal/Modals/PreviewAttachmentModal.component.module.scss
> +    min-height: 300px; /* Minimum height for the container */
I was thinking if the image inside is smaller than the specified dimensions, the container itself will collapse. Therefore, I decided to use min-height and min-width.. but removing them and seems to work as well.

2024-07-07 04:26 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.module.scss
> +    min-height: 300px; /* Minimum height for the container */
@Travisliang001 We can keep the `min-width` and `min-height`. We may need to center the image in the container if the image is smaller than `min-width` and `min-height`.

2024-07-07 04:45 UTC, naturetime10 approved these changes

2024-07-07 04:45 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +        };
```suggestion
        this.state = {};
```

2024-07-07 04:45 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +
```suggestion
```

2024-07-07 05:40 UTC, merged