Allow user to view previous and next attachment
teamyapp/teamy-web pull request #702
Opened 2024-07-17 05:18 UTC by Travisliang001

# Demo
<img width="707" alt="image" src="https://github.com/user-attachments/assets/3c0b24bd-833f-49cf-bb23-f6ccb451e0b0">

[(task:23070)](https://staging.teamyapp.com/teams/107/tasks/23070)

2024-07-17 06:37 UTC, naturetime10 requested changes

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.module.scss
> +$navigationButtonHoverColor: lighten($navigationButtonColor, 20%);
Generally, we set opacity to 80% to have some transparent effect so that user can sort of see the underlying image.

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.module.scss
> +        height: 40px; /* Adjust the size as needed */
```suggestion
        width: 40px;
        height: 40px;
```

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.module.scss
> +        cursor: pointer;
```suggestion
```

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.module.scss
> +        &:hover {
```suggestion

        &:hover {
```

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.module.scss
> +            background-color: $navigationButtonHoverColor;
```suggestion
            opacity: 1;
```

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.module.scss
> +        border-radius: 50%;
```suggestion
        border-radius: 50%;
        opacity: 0.8;
        
```

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.module.scss
> +    }
Is this needed?

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.module.scss
> +    }
Are those needed?

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +    screenHeight: 85, // in Viewport Height
```suggestion
    modalWidth: 90, // in viewport width
    modalHeight: 85, // in viewport height
```

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +                        Image failed to load.
```suggestion
                        Failed to load image.
```

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
>                  }
```suggestion
                }
                
```

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +                    <p className={styles.ContainerText}>
```suggestion
                    <p className={styles.Placeholder}>
```

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +                    <p className={styles.ContainerText}>
```suggestion
                    <p className={styles.Placeholder}>
```

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +                {attachmentIndex !== undefined && attachmentIndex > 0 && (
```suggestion
                {attachmentIndex !== undefined && 
                attachmentIndex > 0 && (
```

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +                        onClick={this.onPrevAttachment}
```suggestion
                        onClick={this.onPreviousClick}
```

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +                        <span className={styles.TooltipText}>Previous</span>
Please use `<ToolTipUI>`

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +                            <span className={styles.TooltipText}>Next</span>
Please use `ToolTipUI`.

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +    private onPrevAttachment = () => {
```suggestion
    private onPreviousClick = () => {
```

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +        if (attachmentIndex !== undefined && attachmentIndex > 0) {
```suggestion

```

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +        }
```suggestion
```

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +        const { screenWidth, screenHeight } = PREVIEW_ATTACHMENT_DIMENSIONS;
Can we add extract the logic between line 64 and line 85 to a new method called `showAttachment(attachment: Attachment)`?

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +            this.open(newAttachment.url, newAttachment.type, newIndex);
Let's invoke showAttachment method to avoid opening modal again?

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +            this.open(newAttachment.url, newAttachment.type, newIndex);
Let's invoke showAttachment method to avoid opening modal again.

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +        if (attachmentIndex !== undefined && attachmentIndex > 0) {
No need to check. As long as the button shows up, this condition is already met.

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +            attachmentIndex < attachments.length - 1
No need to check. As long as the button shows up, this condition is already met.

2024-07-17 06:37 UTC, naturetime10 commented on src/libs/ui/AttachmentList.tsx
> +                index,
```suggestion
                attachment,
                index
```

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +        if (
```suggestion

        if (
```

2024-07-17 06:37 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +        const { attachments } = this.props;
```suggestion
        const { attachments } = this.props;
        
```

2024-07-17 06:38 UTC, naturetime10 commented
Can we rename PR title to `Allow user to view previous and next attachment`?

2024-07-18 03:32 UTC, Travisliang001 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +        if (attachmentIndex !== undefined && attachmentIndex > 0) {
can we use not null assertion here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator

2024-07-18 05:13 UTC, naturetime10 approved these changes

2024-07-18 05:13 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
>      previewAttachmentUrl?: string;
Can we combine `previewAttachmentUrl` and `previewAttachmentType` into `attachment`?

2024-07-18 05:13 UTC, naturetime10 commented on src/components/internal/Modals/PreviewAttachmentModal.component.tsx
> +            previewAttachmentType: attachment.type,
```suggestion
            attachment: attachment,
```

2024-07-18 05:31 UTC, merged